#!/usr/bin/env node
// Material Studio -> Sandustry mod compiler (Step 3).
//
// Input:  a studio graph JSON ({mats, procs, over, dis}) plus a small config.
// Output: a complete mod folder (modinfo.json, main.js, optional worker.js).
//
// What compiles today:
//   - custom materials  -> api.elements.register (matter, density, colors)
//   - heat procs via smelter / dryer -> api.structures.recipes.register
//   - touch procs (mat + mat -> product) -> worker element:moved handlers
//     (the proven Glassworks quench pattern, generalized)
// Anything else (mine drops need terrain, cycles need timers) is reported
// and skipped, never silently dropped.

const fs = require("fs");
const path = require("path");

function shade(c, f) {
  const r = Math.min(255, Math.max(0, Math.round(((c >> 16) & 255) * f)));
  const g = Math.min(255, Math.max(0, Math.round(((c >> 8) & 255) * f)));
  const b = Math.min(255, Math.max(0, Math.round((c & 255) * f)));
  return [r, g, b, 255];
}

// Structure ids in the real game for machines the studio knows.
const MACHINE_STRUCT = { m_smelter: "smelter", m_dryer: "thermodryer" };
const MACHINE_NAME = {
  m_smelter: "Smelter", m_shaker: "Shaker", m_dryer: "Steam Dryer",
  m_mold: "Copper Mold", m_planter: "Planter Box", m_collector: "Collector",
};

function compile(graph, cfg) {
  const report = { ok: [], warn: [], skip: [] };
  const mats = Object.values(graph.mats || {});
  const procs = (graph.procs || []).filter(p => !(graph.dis || []).includes(p.key));
  const matIds = new Set(mats.map(m => m.id));
  const isCustom = id => matIds.has(id);

  // --- classify processes ---
  const recipes = [];   // {structure, input, output, lbl}
  const touches = [];   // {a, b, product, consumeB}  a+b -> product (a is replaced)
  for (const p of procs) {
    if (p.k === "heat" && p.via && MACHINE_STRUCT[p.via]) {
      recipes.push({ structure: MACHINE_STRUCT[p.via], input: p.f, output: p.t, lbl: p.lbl, machine: MACHINE_NAME[p.via] });
      report.ok.push(`recipe: ${p.f} -> ${p.t} via ${MACHINE_NAME[p.via]}`);
    } else if (p.k === "heat" && p.via) {
      report.skip.push(`heat via ${MACHINE_NAME[p.via] || p.via}: that machine's recipes are engine-hardcoded; not compilable yet (${p.f} -> ${p.t})`);
    } else if (p.k === "touch") {
      // convention: note may name the partner; default partner is water
      touches.push({ from: p.f, to: p.t, partner: p.partner || "water", lbl: p.lbl, note: p.note });
      report.warn.push(`touch: ${p.f} -> ${p.t} compiled as "touching water converts" (the studio does not record the partner material yet)`);
    } else {
      report.skip.push(`${p.k}: ${p.f} -> ${p.t} (not compilable yet)`);
    }
  }

  // --- density sanity along machine chains ---
  const byId = {};
  mats.forEach(m => byId[m.id] = m);
  for (const r of recipes) {
    const a = byId[r.input], b = byId[r.output];
    if (a && b && b.d >= a.d) report.warn.push(`density: ${r.output} (${b.d}) is not lighter than ${r.input} (${a.d}) - machine may jam`);
  }

  // --- modinfo ---
  const modinfo = {
    manifestVersion: 1,
    id: cfg.id,
    name: cfg.name,
    version: cfg.version || "0.1.0",
    apiVersion: 1,
    entry: "main.js",
    author: cfg.author || "Brandon",
    description: cfg.description,
    dependencies: [],
    loadOrder: 0,
    configSchema: {
      enabled: { type: "boolean", default: true, labelKey: "Mod enabled", descriptionKey: "Turn the mod off without unsubscribing. Recipes can only be withdrawn at load, so switching off leaves them until the next restart." },
    },
  };
  const needWorker = touches.length > 0;
  if (needWorker) modinfo.workerEntry = "worker.js";

  // --- main.js ---
  const L = [];
  L.push(`// ${cfg.name} - generated by Sandustry Material Studio on ${new Date().toISOString().slice(0, 10)}.`);
  L.push(`// Compiled from the studio graph: ${mats.length} materials, ${recipes.length} recipes, ${touches.length} touch reactions.`);
  L.push(``);
  L.push(`const api = sandkit.api;`);
  L.push(`const MOD_ID = ${JSON.stringify(cfg.id)};`);
  L.push(``);
  L.push(`function setting(key, fallback) {`);
  L.push(`\ttry { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }`);
  L.push(`}`);
  L.push(`const isEnabled = () => setting("enabled", true);`);
  L.push(`function safe(fn) { try { return fn(); } catch (e) { return undefined; } }`);
  L.push(``);
  L.push(`// ------------------------------------------------------------ elements --`);
  L.push(`// NEVER reorder this list; append only. Element type ids are assigned in`);
  L.push(`// registration order and a save remembers them by number.`);
  L.push(`const ELEMENTS = ${JSON.stringify(mats.map(m => ({
    id: m.id, name: m.n, matter: m.m, density: m.d, metaColor: m.c,
    colors: [shade(m.c, 1), shade(m.c, 0.9), shade(m.c, 1.12), shade(m.c, 0.8)],
    fl: m.fl || undefined,
  })), null, "\t")};`);
  L.push(``);
  L.push(`const MatterType = safe(() => sandkit.enums.MatterType) || {};`);
  L.push(`const typeById = new Map();`);
  L.push(`for (const e of ELEMENTS) {`);
  L.push(`\tconst matterType = MatterType[e.matter];`);
  L.push(`\tif (typeof matterType !== "number") { console.error(\`[\${MOD_ID}] unknown matter type "\${e.matter}" for "\${e.id}"\`); continue; }`);
  L.push(`\ttry {`);
  L.push(`\t\tconst def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };`);
  L.push(`\t\tif (e.fl && e.fl.grabbable === false) def.grabbable = false;`);
  L.push(`\t\tif (e.fl && e.fl.transportable === false) def.isTransportable = false;`);
  L.push(`\t\tconst r = api.elements.register(def);`);
  L.push(`\t\tif (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);`);
  L.push(`\t\tconsole.log(\`[\${MOD_ID}] element registered: \${e.id} -> type \${r && r.elementType}\`);`);
  L.push(`\t} catch (err) { console.error(\`[\${MOD_ID}] element "\${e.id}" failed to register:\`, err); }`);
  L.push(`}`);
  L.push(`// Vanilla element types the recipes and reactions reference.`);
  const vanillaRefs = new Set();
  recipes.forEach(r => { if (!isCustom(r.input)) vanillaRefs.add(r.input); if (!isCustom(r.output)) vanillaRefs.add(r.output); });
  touches.forEach(t => { ["from", "to", "partner"].forEach(k => { if (!isCustom(t[k])) vanillaRefs.add(t[k]); }); });
  L.push(`for (const id of ${JSON.stringify([...vanillaRefs])}) {`);
  L.push(`\tconst t = safe(() => api.elements.getTypeFromId(id));`);
  L.push(`\tif (typeof t === "number") typeById.set(id, t);`);
  L.push(`\telse console.error(\`[\${MOD_ID}] vanilla element "\${id}" not found\`);`);
  L.push(`}`);
  L.push(`const typeOf = (id) => typeById.get(id);`);
  L.push(``);
  if (recipes.length) {
    L.push(`// ------------------------------------------------------------- recipes --`);
    L.push(`// One recipe per input per machine is the engine's rule.`);
    L.push(`if (isEnabled()) {`);
    for (const r of recipes) {
      L.push(`\t{`);
      L.push(`\t\tconst input = typeOf(${JSON.stringify(r.input)}), output = typeOf(${JSON.stringify(r.output)});`);
      L.push(`\t\tif (input !== undefined && output !== undefined) {`);
      L.push(`\t\t\ttry {`);
      L.push(`\t\t\t\tapi.structures.recipes.register(${JSON.stringify(r.structure)}, { input, outputs: [{ elementType: output, chance: 1 }] });`);
      L.push(`\t\t\t\tconsole.log(\`[\${MOD_ID}] ${r.machine} recipe: ${r.input} -> ${r.output}\`);`);
      L.push(`\t\t\t} catch (e) { console.error(\`[\${MOD_ID}] recipe ${r.input} -> ${r.output} failed:\`, e); }`);
      L.push(`\t\t}`);
      L.push(`\t}`);
    }
    L.push(`}`);
    L.push(``);
    L.push(`// -------------------------------------------------------------- tooltips --`);
    for (const r of recipes) {
      L.push(`safe(() => api.elements.addInteractionInfo(${JSON.stringify(r.input)}, { kind: "custom", text: ${JSON.stringify(`${r.machine}: ${r.input} → ${r.output}`)} }));`);
    }
  }
  if (needWorker) {
    L.push(``);
    L.push(`// ------------------------------------------- shared state for the worker --`);
    L.push(`let shared = null;`);
    L.push(`try { shared = api.shared.buffers.create("state", { type: "uint32", length: ${8 + touches.length * 3} }); } catch (e) { console.error(\`[\${MOD_ID}] shared buffer failed:\`, e); }`);
    L.push(`function publish() {`);
    L.push(`\tif (!shared) return;`);
    L.push(`\tshared[0] = isEnabled() ? 1 : 0;`);
    touches.forEach((t, i) => {
      L.push(`\tshared[${8 + i * 3}] = typeOf(${JSON.stringify(t.from)}) || 0;`);
      L.push(`\tshared[${9 + i * 3}] = typeOf(${JSON.stringify(t.partner)}) || 0;`);
      L.push(`\tshared[${10 + i * 3}] = typeOf(${JSON.stringify(t.to)}) || 0;`);
    });
    L.push(`}`);
    L.push(`publish(); setInterval(publish, 1000);`);
  }
  L.push(``);
  L.push(`console.log(\`[\${MOD_ID}] loaded\`);`);

  const files = { "modinfo.json": JSON.stringify(modinfo, null, "\t") + "\n", "main.js": L.join("\n") + "\n" };

  if (needWorker) {
    files["worker.js"] = buildWorker(cfg, touches);
  }
  return { files, report };
}

function buildWorker(cfg, touches) {
  // Generalized Glassworks quench: for each touch rule i,
  // shared[8+3i]=from, [9+3i]=partner, [10+3i]=to.
  return `// ${cfg.name} - worker entry (generated). Touch reactions live here because
// only this thread sees particles move.
const api = sandkit.api;
const MOD_ID = ${JSON.stringify(cfg.id)};
let shared = null;
try { shared = api.shared.buffers.require("state", { type: "uint32", length: ${8 + touches.length * 3} }); }
catch (e) { console.error(\`[\${MOD_ID}] worker cannot read shared state:\`, e); }
const N = ${touches.length};
const active = () => shared && shared[0] === 1;
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }
function readType(x, y) { return safe(() => api.elements.getResolvedTypeAtCell(x, y)); }
let writeMode = null;
const WRITERS = [
\t["replaceAtCell", (x, y, t) => api.elements.replaceAtCell(x, y, t)],
\t["removeCreateAtCell", (x, y, t) => { api.elements.removeAtCell(x, y); api.elements.createAtCell(x, y, t); }],
];
function setCell(x, y, t) {
\tfor (const [name, w] of WRITERS) {
\t\tif (writeMode !== null && writeMode !== name) continue;
\t\tsafe(() => w(x, y, t));
\t\tif (readType(x, y) === t) { writeMode = name; return true; }
\t}
\treturn false;
}
const NB = [[0, -1], [0, 1], [-1, 0], [1, 0]];
function scan(x, y) {
\tif (!active() || !shared) return;
\tconst here = readType(x, y);
\tfor (let i = 0; i < N; i++) {
\t\tconst from = shared[8 + i * 3], partner = shared[9 + i * 3], to = shared[10 + i * 3];
\t\tif (!from || !partner || !to) continue;
\t\tif (here !== from && here !== partner) continue;
\t\tfor (const [dx, dy] of NB) {
\t\t\tconst nx = x + dx, ny = y + dy, n = readType(nx, ny);
\t\t\tif (here === from && n === partner) { if (setCell(x, y, to)) return; }
\t\t\telse if (here === partner && n === from) { if (setCell(nx, ny, to)) return; }
\t\t}
\t}
}
function register() {
\tif (!shared || !shared[8]) {
\t\tif (typeof setTimeout === "function") setTimeout(register, 500);
\t\treturn;
\t}
\ttry {
\t\tconst types = new Set();
\t\tfor (let i = 0; i < N; i++) { types.add(shared[8 + i * 3]); types.add(shared[9 + i * 3]); }
\t\tfor (const t of types) {
\t\t\tif (!t) continue;
\t\t\tapi.events.on("element:moved", (p) => { const d = p && p.destination; if (d) scan(d.x, d.y); }, { guard: { elementType: t } });
\t\t}
\t\tconsole.log(\`[\${MOD_ID}] worker armed (\${types.size} watched types)\`);
\t} catch (e) { console.error(\`[\${MOD_ID}] worker subscribe failed:\`, e); }
}
register();
`;
}

// ---- CLI ----
const [graphPath, outDir, cfgPath] = process.argv.slice(2);
const graph = JSON.parse(fs.readFileSync(graphPath, "utf8"));
const cfg = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
const { files, report } = compile(graph, cfg);
fs.mkdirSync(outDir, { recursive: true });
for (const [name, content] of Object.entries(files)) fs.writeFileSync(path.join(outDir, name), content);
console.log("== compiled ==");
for (const k of ["ok", "warn", "skip"]) report[k].forEach(m => console.log(`${k.toUpperCase()}: ${m}`));
console.log("files:", Object.keys(files).join(", "));
