// Manufacturing - hot-load stub (synchronous). Real code: main.real.js.
async function __baked(sandkit) {
// Manufacturing - generated by Sandustry Material Studio on 2026-09-13.
// Compiled from the studio graph: 3 materials, 0 recipes, 0 touch reactions.

const api = sandkit.api;
const MOD_ID = "brandon.manufacturing";

function setting(key, fallback) {
	try { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }
}
const isEnabled = () => setting("enabled", true);
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }

// ------------------------------------------------------------ elements --
// NEVER reorder this list; append only. Element type ids are assigned in
// registration order and a save remembers them by number.
const ELEMENTS = [
	{
		"id": "HeavyStone",
		"name": "Heavy Stone",
		"matter": "Solid",
		"density": 999,
		"metaColor": 0,
		"colors": [
			[
				0,
				0,
				0,
				255
			],
			[
				0,
				0,
				0,
				255
			],
			[
				0,
				0,
				0,
				255
			],
			[
				0,
				0,
				0,
				255
			]
		]
	},
	{
		"id": "glass",
		"name": "Glass",
		"matter": "Solid",
		"density": 140,
		"metaColor": 11842220,
		"colors": [
			[
				180,
				178,
				172,
				255
			],
			[
				162,
				160,
				155,
				255
			],
			[
				202,
				199,
				193,
				255
			],
			[
				144,
				142,
				138,
				255
			]
		]
	},
	{
		"id": "Sand",
		"name": "Sand",
		"matter": "Solid",
		"density": 150,
		"metaColor": 16766814,
		"colors": [
			[
				255,
				215,
				94,
				255
			],
			[
				230,
				194,
				85,
				255
			],
			[
				255,
				241,
				105,
				255
			],
			[
				204,
				172,
				75,
				255
			]
		]
	}
];

const MatterType = safe(() => sandkit.enums.MatterType) || {};
const typeById = new Map();
for (const e of ELEMENTS) {
	const matterType = MatterType[e.matter];
	if (typeof matterType !== "number") { console.error(`[${MOD_ID}] unknown matter type "${e.matter}" for "${e.id}"`); continue; }
	try {
		const def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };
		// The game's own mod elements ALWAYS declare these explicitly - paths
		// like the grabber's release branch on them, and undefined lands wrong
		// (held grains render red, released grains never rejoin the sim).
		def.isGrabbable = !(e.fl && e.fl.grabbable === false);
		def.isTransportable = !(e.fl && e.fl.transportable === false);
		if (e.fl && e.fl.grabbable === false) def.grabbable = false;
		const r = api.elements.register(def);
		if (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);
		console.log(`[${MOD_ID}] element registered: ${e.id} -> type ${r && r.elementType}`);
	} catch (err) { console.error(`[${MOD_ID}] element "${e.id}" failed to register:`, err); }
}
// Vanilla element types the recipes and reactions reference.
for (const id of ["sunsand","sand","wetSand"]) {
	const t = safe(() => api.elements.getTypeFromId(id));
	if (typeof t === "number") typeById.set(id, t);
	else console.error(`[${MOD_ID}] vanilla element "${id}" not found`);
}
const typeOf = (id) => typeById.get(id);


// -------------------------------------------- vanilla element makeovers --
// updateDefinition on a LIVE element type Object.assigns into the engine's
// definition table and broadcasts to every sim/render worker. The catch:
// at mod-load time the worker pool does not exist yet, so a single early
// call updates only the main thread (names, tooltips) and the COLOR change
// never reaches the renderer. Re-applying on a schedule catches the workers
// once they spawn - the call is idempotent, and the renderer reads the
// scheme live, so every existing grain recolors the moment it lands.
function applyMakeovers() {
	if (!isEnabled()) return;
	{
		const t = typeOf("sand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "soil" }));
		}
	}
	{
		const t = typeOf("wetSand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "Wet Soil" }));
		}
	}
	console.log(`[${MOD_ID}] vanilla makeovers applied (sand, wetSand)`);
}
applyMakeovers();
// Event-driven, not polled: the game emits "game:ready" when a world
// session is fully initialized (its own internal mods hook the same
// event for world-init work). Apply once there, plus one safety pass.
safe(() => api.events.on("game:ready", () => safe(applyMakeovers)));
setTimeout(applyMakeovers, 4000);

// ---------------------------------------------- terrain output swaps --
// The Glassworks v0.10 pattern: terrains.updateDefinition replaces what a
// broken terrain cell spawns, live, across all sim threads.
if (isEnabled()) {
	{
		const out = typeOf("Sand");
		if (typeof out === "number") {
			const ok = safe(() => (api.terrains.updateDefinition("dune", { output: { elementType: out, chance: 1 } }), true));
			if (ok) console.log(`[${MOD_ID}] dune now drops Sand`);
			else console.error(`[${MOD_ID}] dune output swap failed`);
		}
	}
}

// ------------------------------------------- shared state for the worker --
let shared = null;
try { shared = api.shared.buffers.create("state", { type: "uint32", length: 10 }); } catch (e) { console.error(`[${MOD_ID}] shared buffer failed:`, e); }
function publish() {
	if (!shared) return;
	shared[0] = isEnabled() ? 1 : 0;
	shared[8] = typeOf("sunsand") || 0;
	shared[9] = typeOf("Sand") || 0;
}
publish(); setInterval(publish, 1000);

// Version banner: toast once when the player is actually in the world -
// the visible proof of exactly which build is running.
{
	let bannered = false;
	const bannerTimer = setInterval(() => {
		if (bannered) return clearInterval(bannerTimer);
		const active = safe(() => api.scene.getActive());
		const Scene = safe(() => sandkit.enums.Scene) || {};
		const menus = [Scene.MainMenu, Scene.Intro].filter(v => typeof v === "number");
		const inWorld = active !== undefined && active !== null && (menus.length ? !menus.includes(active) : active > 2);
		if (!inWorld) return;
		bannered = true;
		safe(() => api.ui.toast("Manufacturing v0.16.2 running"));
	}, 800);
}
console.log(`[${MOD_ID}] loaded`);


// =========================================================================
// MOD TOOLS (testing) - ported from Glassworks, combined into ONE upgrade.
//
// A single free research node, "Mod Tools", hangs off the Shaker (the first
// node at the top of the tree). Researching it unlocks everything at once:
//   - the Matter Gun: a real hotbar item that fires any material; a picker
//     bar appears at the bottom of the screen while it is in hand
//   - vacuum tank delete buttons: a small x on every tank in the Tanks box
//   - the Omni Vacuum: sucks ANY material (liquids, gases, statics, the
//     untransportable - never structures) and multiplies tank storage x10,
//     with the % readout rescaled to the big capacity
// =========================================================================

function inGame() {
	const active = safe(() => api.scene.getActive());
	if (active === undefined || active === null) return true;
	const Scene = safe(() => sandkit.enums.Scene) || {};
	const menus = [Scene.MainMenu, Scene.Intro].filter((v) => typeof v === "number");
	if (menus.length > 0) return !menus.includes(active);
	return active !== 1 && active !== 2;
}

const TECH_TOOLS = "brandonModTools";
const toolsUnlocked = () => safe(() => api.tech.isLockedById(TECH_TOOLS)) === false;

// --- the Matter Gun ---
const GUN = "brandonMatterGun";
const AS = safe(() => sandkit.enums.ActionState) || { Start: 1, Active: 2, End: 3 };
const ReactM = safe(() => sandkit.react);
const hM = ReactM ? ReactM.createElement : null;

let gunPalette = [];
let gunType = null;
function buildGunPalette() {
	const types = safe(() => api.elements.getRegisteredTypes(), []) || [];
	const MT = safe(() => sandkit.enums.MatterType) || {};
	gunPalette = types
		.map((type) => {
			const def = safe(() => api.elements.getDefinitionByType(type)) || {};
			const metaColor = typeof def.metaColor === "number" ? def.metaColor : null;
			return {
				type,
				name: safe(() => api.elements.getNameByType(type), null) || `type ${type}`,
				matterType: def.matterType,
				color: metaColor === null ? "#8a8a8a" : `#${metaColor.toString(16).padStart(6, "0")}`,
			};
		})
		.filter((p) => p.matterType !== (safe(() => sandkit.enums.MatterType.Particle)))
		// never the Screensaver's tracer copies: they exist only for the Sandbox Loop to emit.
		// The game's own "keep out of pickers" flag, plus their ids in case the flag was dropped
		.filter((p) => !(safe(() => api.elements.getDefinitionByType(p.type).showInFilterPicker) === false || /^brandonTrc_|^brandonTracer/.test(safe(() => api.elements.getIdByType(p.type)) || "")))
		.sort((a, b) => a.name.localeCompare(b.name));
	if (gunType === null && gunPalette.length > 0) gunType = gunPalette[0].type;
}
buildGunPalette();
setTimeout(buildGunPalette, 3000); // catch late registrations

try {
	await api.sprites.loadFromMod(GUN, "matter_gun.png");
	await api.sprites.loadFromMod(`${GUN}Icon`, "matter_gun_icon.png");
} catch (e) {
	console.error(`[${MOD_ID}] matter gun sprites failed to load:`, e);
}

try {
	api.items.register({
		id: GUN,
		name: "Matter Gun",
		description: "A testing tool that fires any material in the game. Select it and a picker appears at the bottom of the screen - click a swatch to choose what it spews, then hold to spray at the cursor.",
		categoryKey: "utility",
		sprite: { id: GUN, type: "twohand", ui: { imageName: `${GUN}Icon` } },
		handleAction: (e, t) => safe(() => {
			if (!isEnabled()) return;
			if (!e.session.action.state[AS.Active]) return;
			const cell = safe(() => api.input.getMouseCellPosition());
			if (!cell || gunType === null) return;
			safe(() => api.grid.forEachCellInCircle(cell.x, cell.y, 2, (x, y) => {
				safe(() => api.elements.createAtCellWhenIdle(x, y, gunType));
			}));
		}),
	});
	console.log(`[${MOD_ID}] Matter Gun registered`);
} catch (e) {
	console.error(`[${MOD_ID}] Matter Gun registration failed:`, e);
}

function gunInHand() {
	const act = safe(() => api.action.getActive());
	return !!act && typeof act === "object" && String(act.id) === GUN;
}

if (ReactM && hM) {
	function MatterGunPicker() {
		const [, bump] = ReactM.useState(0);
		ReactM.useEffect(() => {
			const id = setInterval(() => bump((v) => v + 1), 150);
			return () => clearInterval(id);
		}, []);
		if (!isEnabled() || !inGame() || !gunInHand()) return null;
		if (gunPalette.length === 0) buildGunPalette();
		return hM("div", {
			style: {
				position: "fixed", left: "50%", bottom: "86px", transform: "translateX(-50%)",
				display: "flex", flexWrap: "wrap", justifyContent: "center", gap: "4px",
				maxWidth: "640px", maxHeight: "96px", overflowY: "auto",
				padding: "6px 8px", background: "rgba(12, 12, 18, 0.88)",
				border: "1px solid rgba(235, 90, 60, 0.55)", borderRadius: "6px",
				zIndex: 1000, pointerEvents: "auto",
				font: "11px monospace", color: "#ddd",
			},
		},
			gunPalette.map((p) =>
				hM("button", {
					key: p.type,
					onClick: () => { gunType = p.type; safe(() => api.ui.toast(`Matter Gun: ${p.name}`)); },
					style: {
						display: "flex", alignItems: "center", gap: "4px",
						padding: "2px 6px", cursor: "pointer", font: "inherit",
						background: gunType === p.type ? "rgba(235, 90, 60, 0.25)" : "rgba(255,255,255,0.06)",
						border: `1px solid ${gunType === p.type ? "rgba(235,90,60,0.9)" : "transparent"}`,
						borderRadius: "3px", color: gunType === p.type ? "#f0a080" : "#ccc",
					},
				},
					hM("span", { style: {
						width: "10px", height: "10px", background: p.color,
						borderRadius: "2px", border: "1px solid rgba(0,0,0,0.6)", flexShrink: 0,
					} }),
					p.name
				)
			)
		);
	}
	safe(() => api.ui.inject("matter-gun-picker", MatterGunPicker)) ||
		console.warn(`[${MOD_ID}] picker injection failed`);
}

// --- vacuum tools: tank delete buttons + omni-suck, gated on the same node ---
const ItemTypeE = safe(() => sandkit.enums.ItemType) || {};
const ItemIdE = safe(() => sandkit.enums.ItemId) || {};

function vacuumItem() {
	const inv = safe(() => sandkit.state.store.player.inventory);
	if (!Array.isArray(inv)) return null;
	return inv.find((it) => it && it.itemType === ItemTypeE.Tool && it.id === ItemIdE.Vacuum) || null;
}
function vacuumInHand() {
	const act = safe(() => api.action.getActive());
	return !!act && typeof act === "object" && act.id === ItemIdE.Vacuum;
}
const omniUnlocked = toolsUnlocked; // one node rules them all
const refreshHotbar = () => safe(() => api.ui.overlays.update("hotbar"));
const VAC_CAPS = [500, 1000, 1500, 2000, 2500, 3000];
function vacuumCap() {
	const lvl = safe(() => api.upgrades.getLevelById("vacuum", "capacity"), 0) || 0;
	return VAC_CAPS[Math.max(0, Math.min(VAC_CAPS.length - 1, lvl))];
}
const omniCap = () => vacuumCap() * 10;

function tanksSectionRow() {
	const label = safe(() => api.i18n.t("ui|vacuum|tanksSection"), null) || "Tanks";
	const spans = document.querySelectorAll("span");
	for (const span of spans) {
		if (span.textContent !== label) continue;
		const sib = span.nextElementSibling;
		const row = sib && sib.firstElementChild;
		if (row && row.children.length > 0) return { span, row };
	}
	return null;
}

function graftTankButtons() {
	if (!isEnabled() || !inGame() || !vacuumInHand()) return;
	if (!toolsUnlocked()) return; // whole toolkit sits behind the one node
	const item = vacuumItem();
	const tanks = item && item.data && Array.isArray(item.data.tanks) ? item.data.tanks : null;
	if (!tanks) return;
	const found = tanksSectionRow();
	if (!found) return;
	const { span, row } = found;
	if (omniUnlocked() && !span.querySelector(".gw-omni")) {
		const tag = document.createElement("span");
		tag.className = "gw-omni";
		tag.textContent = " OMNI";
		tag.style.cssText = "color:#8fd0ff;font-size:9px;margin-left:6px;letter-spacing:0.5px;";
		span.appendChild(tag);
	}
	const cells = row.children;
	if (omniUnlocked()) {
		const capX = omniCap();
		const pctOf = (amount) => (capX > 0 ? Math.min(100, Math.round((amount / capX) * 100)) : 0);
		const fixAll = (rootEl, pct) => {
			for (const el of rootEl.querySelectorAll("*")) {
				if (el.classList && el.classList.contains("gw-tank-x")) continue;
				if (el.style && typeof el.style.height === "string" && /%$/.test(el.style.height))
					el.style.height = pct + "%";
				if (el.children.length === 0 && /^\d{1,4}\s*%$/.test((el.textContent || "").trim()))
					el.textContent = pct + "%";
			}
		};
		for (let i = 0; i < cells.length && i < tanks.length; i++) {
			fixAll(cells[i], pctOf((tanks[i] && tanks[i].amount) || 0));
		}
		const rootBox = row.closest('[class*="inline-flex"]');
		if (rootBox) {
			const ai = typeof item.data.activeTankIdx === "number" ? item.data.activeTankIdx : 0;
			const at = tanks[Math.max(0, Math.min(tanks.length - 1, ai))];
			const pct = pctOf((at && at.amount) || 0);
			for (const el of rootBox.querySelectorAll("*")) {
				if (row.contains(el) || (el.classList && el.classList.contains("gw-tank-x"))) continue;
				if (el.children.length === 0 && /^\d{1,4}\s*%$/.test((el.textContent || "").trim()))
					el.textContent = pct + "%";
			}
		}
	}
	for (let i = 0; i < cells.length && i < tanks.length; i++) {
		const cell = cells[i];
		if (cell.querySelector(".gw-tank-x")) continue;
		if (!cell.style.position) cell.style.position = "relative";
		const btn = document.createElement("button");
		btn.className = "gw-tank-x";
		btn.type = "button";
		btn.textContent = "✕";
		btn.title = "Delete this tank's contents";
		btn.style.cssText =
			"position:absolute;top:-5px;right:-5px;width:13px;height:13px;line-height:11px;" +
			"padding:0;font-size:9px;text-align:center;cursor:pointer;z-index:5;" +
			"background:rgba(20,20,26,0.9);color:#f08080;border:1px solid rgba(235,60,60,0.7);" +
			"border-radius:50%;";
		const idx = i;
		btn.addEventListener("mousedown", (e) => { e.stopPropagation(); });
		btn.addEventListener("click", (e) => {
			e.stopPropagation();
			e.preventDefault();
			const it = vacuumItem();
			const ts = it && it.data && Array.isArray(it.data.tanks) ? it.data.tanks : null;
			if (ts && ts[idx]) {
				ts[idx].elementType = 0;
				ts[idx].amount = 0;
				refreshHotbar();
				safe(() => api.ui.toast(`Tank ${idx + 1} deleted`));
			}
		});
		cell.appendChild(btn);
	}
}
safe(() => setInterval(() => safe(graftTankButtons), 120));

let vacMouseDown = false;
safe(() => {
	window.addEventListener("mousedown", (e) => { if (e.button === 0) vacMouseDown = true; });
	window.addEventListener("mouseup", (e) => { if (e.button === 0) vacMouseDown = false; });
	window.addEventListener("blur", () => { vacMouseDown = false; });
});
let omniFrame = 0;
function omniSuck() {
	requestAnimationFrame(omniSuck);
	if (omniFrame++ % 3 !== 0) return;
	if (!isEnabled() || !vacMouseDown || !inGame()) return;
	if (!vacuumInHand() || !omniUnlocked()) return;
	const item = vacuumItem();
	const tanks = item && item.data && Array.isArray(item.data.tanks) ? item.data.tanks : null;
	if (!tanks) return;
	const cell = safe(() => api.input.getMouseCellPosition());
	if (!cell) return;
	const MT = safe(() => sandkit.enums.MatterType) || {};
	let collected = 0;
	safe(() => api.grid.forEachCellInCircle(cell.x, cell.y, 5, (x, y) => {
		if (collected >= 20) return;
		const info = safe(() => api.elements.getInfoAtCell(x, y));
		if (!info || typeof info.elementType !== "number" || info.elementType === 0) return;
		const def = safe(() => api.elements.getDefinitionByType(info.elementType)) || {};
		const blockedByVanilla =
			def.matterType === MT.Liquid || def.matterType === MT.Gas ||
			def.matterType === MT.Static || def.isTransportable === false;
		const base = vacuumCap(), max = base * 10;
		const floor = blockedByVanilla ? 0 : base;
		let tank = tanks.find((t) => t.elementType === info.elementType && t.amount >= floor && t.amount < max);
		if (!tank && blockedByVanilla) tank = tanks.find((t) => t.elementType === 0 || t.amount <= 0);
		if (!tank) return;
		if (tank.elementType !== info.elementType) { tank.elementType = info.elementType; tank.amount = Math.max(0, tank.amount); }
		tank.amount++;
		collected++;
		safe(() => api.elements.removeAtCellWhenIdle(x, y));
	}));
	if (collected > 0) refreshHotbar();
}
safe(() => requestAnimationFrame(omniSuck));

// --- the ONE free research node, behind the first node at the top (Shaker) ---
{
	const parent = safe(() => sandkit.enums.Tech.Shaker);
	if (parent !== undefined && parent !== null && !safe(() => api.tech.getDefinitionById(TECH_TOOLS))) {
		safe(() => api.i18n.register("en", {
			[`tech|${TECH_TOOLS}|name`]: "Mod Tools",
			[`tech|${TECH_TOOLS}|description`]:
				"Free testing toolkit, all in one: the Matter Gun (fires any material - a picker appears while it is in hand), delete buttons on every vacuum tank, and the Omni Vacuum - sucks ANY material, liquids and gases included, with 10x tank storage. Structures stay safe.",
		}));
		const definition = {
			nameKey: `tech|${TECH_TOOLS}|name`,
			descriptionKey: `tech|${TECH_TOOLS}|description`,
			cost: 0,
			currencyType: "gold",
			branch: "heat",
			requires: [parent],
			unlocks: { items: [GUN] },
		};
		// The Shaker root sits at grid {row 0, col 4} (verified in the tree code):
		// park Mod Tools right beside it on the top row, walking outward until a
		// cell is free. Occupied cells throw, so the loop just tries the next.
		let done = false;
		for (const preferredPosition of [{ row: 0, col: 5 }, { row: 0, col: 3 }, { row: 0, col: 6 }, { row: 0, col: 2 }, { row: 1, col: 4 }, null]) {
			try {
				api.tech.registerNode(TECH_TOOLS, definition,
					preferredPosition ? { parentId: parent, preferredPosition } : { parentId: parent });
				console.log(`[${MOD_ID}] research node registered: Mod Tools (free, off the Shaker)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Mod Tools node could not be placed`);
	}
}

// =========================================================================
// GRAB HEAVY STONE toggle - a switch shown in the Grabber's control bar. On
// (default) the Grabber works normally; off, Heavy Stone becomes un-grabbable
// (isGrabbable=false) so the Grabber leaves it in place. The grabber checks the
// element's isGrabbable flag, and updateDefinition flips it live.
const HEAVY_ID = "HeavyStone";
let grabHeavy = true;
try { if (window.localStorage.getItem("brandon.grabHeavy") === "0") grabHeavy = false; } catch (e) {}

function heavyType() { return safe(() => api.elements.getTypeFromId(HEAVY_ID)); }
function applyGrabHeavy() {
	const t = heavyType();
	if (typeof t !== "number") return;
	safe(() => api.elements.updateDefinition(t, { isGrabbable: grabHeavy, grabbable: grabHeavy }));
}
function setGrabHeavy(on) {
	grabHeavy = !!on;
	try { window.localStorage.setItem("brandon.grabHeavy", grabHeavy ? "1" : "0"); } catch (e) {}
	applyGrabHeavy();
	safe(() => api.ui.toast("Grab Heavy Stone: " + (grabHeavy ? "on" : "off")));
}
// Re-assert the flag after the element exists (registration + save load).
safe(() => api.events.on("game:ready", () => setTimeout(applyGrabHeavy, 600)));
if (typeof setTimeout === "function") setTimeout(applyGrabHeavy, 1600);

const GrabberItemId = safe(() => sandkit.enums.ItemId && sandkit.enums.ItemId.Grabber);
function grabberInHand() {
	const act = safe(() => api.action.getActive());
	return !!act && typeof act === "object" && act.id === GrabberItemId;
}

if (ReactM && hM) {
	function GrabHeavyToggle() {
		const [, bump] = ReactM.useState(0);
		ReactM.useEffect(() => { const id = setInterval(() => bump((v) => v + 1), 200); return () => clearInterval(id); }, []);
		if (!isEnabled() || !inGame() || !grabberInHand()) return null;
		if (typeof heavyType() !== "number") return null;
		// Styled to match the game's own grabber bar (dark pill, sans font,
		// Shaking-style checkbox), parked just above it so it reads as part of
		// that menu. The grabber bar is a floating overlay too, so this is as
		// "attached" as the API allows.
		return hM("div", {
			style: {
				position: "fixed", left: "50%", bottom: "258px", transform: "translateX(-50%)",
				display: "flex", alignItems: "center", gap: "8px",
				padding: "7px 14px", background: "rgba(10,14,20,0.92)",
				border: "1px solid rgba(255,255,255,0.14)", borderRadius: "10px",
				zIndex: 1000, pointerEvents: "auto",
				font: '600 13px -apple-system, "Segoe UI", Roboto, sans-serif', letterSpacing: "0.01em",
				color: grabHeavy ? "#eef1f5" : "#8b93a0", cursor: "pointer", userSelect: "none",
				boxShadow: "0 2px 10px rgba(0,0,0,0.4)",
			},
			onClick: () => setGrabHeavy(!grabHeavy),
			title: "When off, the Grabber can't pick up Heavy Stone",
		},
			hM("span", {
				style: {
					display: "inline-flex", alignItems: "center", justifyContent: "center",
					width: "15px", height: "15px", flexShrink: 0, borderRadius: "3px",
					border: "1.5px solid " + (grabHeavy ? "rgba(255,255,255,0.8)" : "rgba(255,255,255,0.4)"),
					background: grabHeavy ? "#ffd75e" : "transparent",
					color: "#101318", fontSize: "11px", fontWeight: "800", lineHeight: "1",
				},
			}, grabHeavy ? "✓" : ""),
			"Grab Heavy Stone"
		);
	}
	safe(() => api.ui.inject("grab-heavy-toggle", GrabHeavyToggle)) ||
		console.warn(`[${MOD_ID}] grab-heavy toggle injection failed`);
}



// =========================================================================
// MANUFACTURING & GLASS research
//
// Manufacturing sits immediately LEFT of the Smelter in the tech tree
// (Smelter is grid row 13, col 1 - verified in the vanilla layout table),
// and is the trunk future branches will hang off. GLASS is its first
// child: researching it registers the Sand -> Glass smelter recipe, which
// does not exist until then - un-researched, the Smelter ignores Sand.
// =========================================================================

const TECH_MANU = "brandonManufacturing";
const TECH_GLASS = "brandonGlassTech";

safe(() => api.i18n.register("en", {
	[`tech|${TECH_MANU}|name`]: "Manufacturing",
	[`tech|${TECH_MANU}|description`]:
		"Industrial processing of raw desert materials. Unlocks the manufacturing branch - Glass first, more to come.",
	[`tech|${TECH_GLASS}|name`]: "Glass",
	[`tech|${TECH_GLASS}|description`]:
		"Glassmaking. The Smelter learns to convert Sand 1:1 into Glass, a pale solid just light enough to clear the machine.",
}));

// Manufacturing - left of the Smelter (row 13, col 0), child of Smelter tech.
{
	const parent = safe(() => sandkit.enums.Tech.Smelter);
	if (parent !== undefined && parent !== null && !safe(() => api.tech.getDefinitionById(TECH_MANU))) {
		const definition = {
			nameKey: `tech|${TECH_MANU}|name`,
			descriptionKey: `tech|${TECH_MANU}|description`,
			cost: 250,
			currencyType: "gold",
			branch: "heat",
			requires: [parent],
			unlocks: {},
		};
		let done = false;
		for (const preferredPosition of [{ row: 13, col: 0 }, { row: 14, col: 1 }, { row: 12, col: 0 }, null]) {
			try {
				api.tech.registerNode(TECH_MANU, definition,
					preferredPosition ? { parentId: parent, preferredPosition } : { parentId: parent });
				console.log(`[${MOD_ID}] research node registered: Manufacturing (left of the Smelter)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Manufacturing node could not be placed`);
	}
}

// Glass - first branch under Manufacturing (row 14, col 0).
{
	if (safe(() => api.tech.getDefinitionById(TECH_MANU)) && !safe(() => api.tech.getDefinitionById(TECH_GLASS))) {
		const definition = {
			nameKey: `tech|${TECH_GLASS}|name`,
			descriptionKey: `tech|${TECH_GLASS}|description`,
			cost: 500,
			currencyType: "gold",
			branch: "heat",
			requires: [TECH_MANU],
			unlocks: {},
		};
		let done = false;
		for (const preferredPosition of [{ row: 14, col: 0 }, { row: 15, col: 0 }, { row: 15, col: 1 }, null]) {
			try {
				api.tech.registerNode(TECH_GLASS, definition,
					preferredPosition ? { parentId: TECH_MANU, preferredPosition } : { parentId: TECH_MANU });
				console.log(`[${MOD_ID}] research node registered: Glass (under Manufacturing)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Glass node could not be placed`);
	}
}

// The gated recipe: the Smelter learns Sand -> Glass only once GLASS is
// researched. Recipe registration is dynamic (the registry broadcasts to the
// sim threads), so a light poll arms it the moment the node unlocks - this
// session or any later one.
let glassRecipeArmed = false;
function armGlassRecipe() {
	if (glassRecipeArmed || !isEnabled()) return;
	if (safe(() => api.tech.isLockedById(TECH_GLASS)) !== false) return;
	const input = typeOf("Sand"), output = typeOf("glass");
	if (input === undefined || output === undefined) return;
	try {
		api.structures.recipes.register("smelter", { input, outputs: [{ elementType: output, chance: 1 }] });
		safe(() => api.elements.addInteractionInfo("Sand", { kind: "custom", text: "Smelter: Sand → Glass" }));
		safe(() => api.ui.toast("Glass researched - the Smelter now converts Sand into Glass"));
		console.log(`[${MOD_ID}] Glass researched: smelter recipe Sand -> Glass armed`);
	} catch (e) {
		console.error(`[${MOD_ID}] gated glass recipe failed to register:`, e);
	}
	glassRecipeArmed = true;
}
armGlassRecipe();
setInterval(armGlassRecipe, 1500);

// =========================================================================
// FILTER MK.3 - its own building: the Mk.2 Filter's sorting at Mk.2 BELT speed
//
// Everything that makes the Mk.2 Filter a filter is the game's own, reused:
//  - sorting: the sim marks a tile as a filter for ANY structure that carries a
//    `filter` object (allow/block, element list, liquid/gas flags), so a Mk.3
//    gets exactly the Mk.2's rules by carrying the same object. It is copied
//    from the Mk.2 Filter panel's current setting when placed (as the game does
//    for its own filter wall); copy-paste keeps a Mk.3's own filter.
//  - moving: registered as a conveyor type, the sim runs the same move routine
//    as every belt (row above the structure, 1 cell per pass). Mod belt types are
//    not in the game's belt passes, so a manager-worker trigger posts the pass
//    every 166 ms, right then left - the Mk.2 Conveyor Belt's cadence (the Mk.2
//    Filter runs every 332 ms). Clearing Frames are driven the same way.
//  - placed vertically it becomes a normal Mk.2 filter wall, like the Mk.2 Filter.
//  - look: the Mk.2 sprite with blue -> red, animated from the Mk.2 CONVEYOR BELT's
//    own frame counter (mirrored into a shared buffer the renderer reads).
//  - menu: the game's filter panel only opens for its own ids (a fixed list), so
//    the Mk.3 has a copy of it below - same bar, same picker, same setting.
// Unlocked by the FILTER MK.3 research.
// (0.10.0 - 0.12.2 sped up EVERY Mk.2 Filter instead; removed in 0.13.0.)
// =========================================================================
const TECH_FILTER_MK3 = "brandonFilterMk3";
const FILTER_MK3_COST = 25000;    // placeholder price - to be tuned later
const MK3_R = "filterRightMk3", MK3_L = "filterLeftMk3";
const MK3_BELT_MS = 166;          // the Mk.2 Conveyor Belt's pass (transport.passes.beltsMk2)
safe(() => api.i18n.register("en", {
	[`tech|${TECH_FILTER_MK3}|name`]: "Filter Mk.3",
	[`tech|${TECH_FILTER_MK3}|description`]:
		"Unlocks the Filter Mk.3: sorts exactly like the Mk.2 Filter, but moves material as fast as a Mk.2 Conveyor Belt.",
	["structures|brandonFilterMk3|name"]: "Filter Mk.3",
	["structures|brandonFilterMk3|description"]:
		"Sorts exactly like the Mk.2 Filter, at Mk.2 Conveyor Belt speed. Pick its materials in the panel above the hotbar, or click a placed row to change it. Placed vertically it makes a filter wall.",
}));
// Animation: the renderer steps a mod structure's frames from a shared buffer
// (render.spritesheet.frameBuffer). Buffer names are namespaced per mod, so the game's
// own conveyorMk2AnimationIndex can't be named - it is copied into this one every
// frame. [0] = left, [1] = right, as the manager worker counts them.
let mk3Anim = null;
try { mk3Anim = api.shared.buffers.create("mk3anim", { type: "uint8", length: 2 }); }
catch (e) { console.error(`[${MOD_ID}] Filter Mk.3 animation buffer failed:`, e); }
safe(() => api.events.on("frame:render", () => {
	const src = mk3Anim && sandkit.state.shared.mods.conveyorMk2AnimationIndex;
	if (src) { mk3Anim[0] = src[0]; mk3Anim[1] = src[1]; }
}));
let mk3Ready = false;
try {
	await api.sprites.loadFromMod("brandon_filter_right_mk3", "filter_right_mk3.png");
	await api.sprites.loadFromMod("brandon_filter_left_mk3", "filter_left_mk3.png");
	// 0.16.1: the icon (tech tree, build menu, hotbar) is ONE frame. Without render.ui.imageName the
	// game's icons use render.imageName - the whole 4-frame strip - and showed four filters
	// side by side. filter_right_mk3_icon.png is frame 0 of the strip, pixel for pixel.
	let mk3Icon = null;
	try { await api.sprites.loadFromMod("brandon_filter_right_mk3_icon", "filter_right_mk3_icon.png"); mk3Icon = "brandon_filter_right_mk3_icon"; }
	catch (e) { console.error(`[${MOD_ID}] Filter Mk.3 icon failed to load (the icon shows the whole strip):`, e); }
	const variants = [{ id: MK3_L, angles: [-180, 180] }, { id: MK3_R, angles: [0] }, { id: "filterWallMk2", angles: [-90, 90] }];
	const common = { nameKey: "structures|brandonFilterMk3|name", descriptionKey: "structures|brandonFilterMk3|description", name: "Filter Mk.3",
		categoryKey: "logistics", tooltipHover: { type: "filter" }, variants };
	// the strip is 4 frames of 18x18, the Mk.2's belt animation; frameBuffer picks the frame
	const sheet = (index) => mk3Anim ? { frames: 4, frameSize: { width: 18, height: 18 }, frameBuffer: { key: "mk3anim", index } } : { frames: 4, frameSize: { width: 18, height: 18 }, intervalMs: MK3_BELT_MS };
	// blockGridType: the sim sees a Mk.3 tile as a Mk.2 belt (see "Moving" below); everything
	// outside the sim grid (menus, labels, saves, the Copier) still sees filterRightMk3
	api.structures.register(Object.assign({ id: MK3_R, order: 52, blockGridType: "conveyorRightMk2",
		buildModes: [{ type: "line", directions: ["horizontal"] }, { type: "line", directions: ["vertical"] }],
		render: { imageName: "brandon_filter_right_mk3", size: { width: 18, height: 18 }, offset: { x: -1, y: -1 }, z: .85, spritesheet: sheet(1), ui: Object.assign({ outline: true, width: "18px", height: "18px" }, mk3Icon ? { imageName: mk3Icon, size: { width: 18, height: 18 } } : null) } }, common));
	api.structures.register(Object.assign({ id: MK3_L, blockGridType: "conveyorLeftMk2",
		render: { imageName: "brandon_filter_left_mk3", size: { width: 18, height: 18 }, offset: { x: -1, y: -1 }, z: .85, spritesheet: sheet(0) } }, common));
	mk3Ready = true;
} catch (e) { console.error(`[${MOD_ID}] Filter Mk.3 structures failed to register:`, e); }
// Moving: 0.16.2 - the simulation grid stores a Mk.3 tile AS a Mk.2 belt tile (blockGridType,
// in the register calls above), so the game's own Mk.2 belt pass moves it: same speed, same
// schedule, and - what mattered - the same sweep as the belts around it, column by column,
// downstream first. Its filter object still sorts (the grid's filter bits come from the
// structure's `filter`, not its type) - a Mk.2 Filter that moves like a Mk.2 belt.
// Until 0.16.1 it was a mod conveyor type moved by its own 166 ms trigger
// ("brandonFilterMk3Belts"): a separate sweep, so whenever the belt's sweep ran first the
// belt's front column found the Mk.3's first cell still full - grains queued in front of it
// and went through one or two at a time.
// a new Mk.3 takes the Mk.2 Filter panel's current setting (the game's own default filter)
safe(() => api.events.on("building:placed", (p) => {
	const s = p && p.structure;
	if (!s || (s.type !== MK3_R && s.type !== MK3_L) || s.filter) return;
	const df = safe(() => sandkit.state.store.options.defaultFilter) || { mode: "allow" };
	s.filter = Object.assign({}, df, { affectsLiquid: true, affectsGas: true });
	if (Array.isArray(s.filter.elementType)) s.filter.elementType = s.filter.elementType.slice();
}));
// --- the Mk.3 is one of the game's own filters -------------------------------------------
// The game decides "is this a filter?" with short id lists inside its bundle (Mk.1, Mk.2,
// the walls, plus one in the hotbar code) that no api exposes; its filter panel, labels
// overlay, row editor ("Edit last placed" included), hotbar handling and copy-paste all ask
// them - and they ask with Array.prototype.includes. So that one call is taught one fact:
// a Mk.3 is in every list its Mk.2 twin is in (filterRightMk3 wherever filterRightMk2 is,
// filterLeftMk3 wherever filterLeftMk2 is). Any other question goes straight through (two
// string compares, then the original). The Copier's left/right pair list is read through
// a Map, not includes, so a Mk.3 is never flipped into a Mk.2.
// 0.16.1: ONLY for a list that holds nothing but filter ids - the game's filter lists do (Mk.1 =
// StructureType FilterLeft/Right, the Mk.2s, the walls). 0.16.0 answered for ANY array, so
// store.player.buildings - which holds filterRightMk2 - "already had" filterRightMk3: buying the
// research (the game unlocks with `buildings.includes(id) || buildings.push(id)`) and the
// unlock fallback below both skipped it, and the Mk.3 never reached the build menu.
const MK3_TWIN = { [MK3_R]: "filterRightMk2", [MK3_L]: "filterLeftMk2" };
const ST = safe(() => sandkit.enums.StructureType) || {};
const FILTER_IDS = new Set(["filterLeftMk2", "filterRightMk2", "filterWall", "filterWallMk2", MK3_R, MK3_L, "filterLeft", "filterRight"]
	.concat([ST.FilterLeft, ST.FilterRight].filter((v) => v !== undefined && v !== null)));
let filterListsOk = false;
try {
	if (!Array.prototype.includes.__brandonMk3v2) {   // once per page, even if the mod is reloaded
		const orig = Array.prototype.includes.__brandonOrig || Array.prototype.includes;   // a 0.16.0 patch from this page is replaced, not stacked
		const onlyFilters = (a) => { if (a.length === 0 || a.length > 16) return false; for (let i = 0; i < a.length; i++) if (!FILTER_IDS.has(a[i])) return false; return true; };
		const includes = function includes(v, from) {
			if ((v === MK3_R || v === MK3_L) && Array.isArray(this) && onlyFilters(this) && orig.call(this, MK3_TWIN[v])) return true;
			return orig.call(this, v, from);
		};
		Object.defineProperty(includes, "__brandonMk3", { value: true });
		Object.defineProperty(includes, "__brandonMk3v2", { value: true });
		Object.defineProperty(includes, "__brandonOrig", { value: orig });
		Object.defineProperty(Array.prototype, "includes", { value: includes, writable: true, configurable: true, enumerable: false });
	}
	filterListsOk = ["filterRightMk2"].includes(MK3_R) && !["filterRightMk2"].includes(MK3_L) && [1, 2].includes(2) && [NaN].includes(NaN)
		&& !["filterRightMk2", "conveyorRight"].includes(MK3_R);   // a list of other things (the unlocked buildings) gets the plain answer
} catch (e) { console.error(`[${MOD_ID}] Filter Mk.3: could not join the game's filter lists:`, e); }
// Checked against the game itself once a world is up: its row editor must accept a Mk.3 row.
// If a game update stops using those lists the Mk.3 still sorts and moves (the sim reads the
// filter object), but it would have no menu - say so rather than fail quietly.
let mk3Checked = false;
function checkFilterLists() {
	if (mk3Checked || !mk3Ready || !inGame()) return;
	let s = null; safe(() => api.structures.forEachOfType(MK3_R, (x) => { if (!s && typeof x.x === "number") s = x; }));
	if (!s) safe(() => api.structures.forEachOfType(MK3_L, (x) => { if (!s && typeof x.x === "number") s = x; }));
	if (!s) return;   // nothing placed yet to test with
	if (safe(() => sandkit.state.session.building.placing)) return;   // selectAt cancels a placement: wait until none is under way
	mk3Checked = true;
	const ed = safe(() => sandkit.engine.api.filterGroupEditor), st = safe(() => sandkit.engine.state);
	if (!ed || safe(() => ed.getSelection(st))) return;   // no editor, or it is busy with a row: don't disturb it
	const fx = safe(() => st.session.building.filterForceExpand);
	const ok = !!safe(() => ed.selectAt(st, s.x, s.y, { toggle: false }));
	safe(() => ed.cancel(st)); safe(() => { st.session.building.filterForceExpand = fx; });
	if (!filterListsOk || !ok) {
		console.error(`[${MOD_ID}] Filter Mk.3: the game's filter editor does not accept a Mk.3 (lists ok: ${filterListsOk}) - a game update may have changed how it recognises filters`);
		safe(() => api.ui.toast("Manufacturing: the Filter Mk.3 menu isn't working with this game version - it still sorts, but tell Brandon"));
	}
}
setInterval(checkFilterLists, 3000);
safe(() => api.events.on("game:ready", () => { mk3Checked = false; }));
// Two spots name the Mk.2 outright instead of asking a list:
// - picking a material in the game's filter panel (not while editing a row) sets the held
//   building to "filterRightMk2" - that would swap a held Mk.3 for a Mk.2, so it is put back
//   (the Mk.3 is still what the build menu / hotbar says is held);
// - taking a Mk.2 from the build menu sets filterForceExpand (the panel opens expanded) -
//   done here for the Mk.3 too. (The hotbar already does it: its check is a list.)
let heldMk3 = null;
function mk3InHandBySource() {
	const pl = safe(() => sandkit.state.store.player); if (!pl) return false;
	const a = pl.action;
	if (a && (a.id === MK3_R || a.id === MK3_L)) return true;
	const hb = pl.hotbar, it = safe(() => hb.bars[hb.hotbarIndex][hb.activeSlotIndex]);
	return !!(it && (it.id === MK3_R || it.id === MK3_L));
}
safe(() => api.events.on("frame:render", () => {
	const b = safe(() => sandkit.state.session.building); if (!b) return;
	const a = b.activeStructureType;
	if (a === MK3_R || a === MK3_L) {
		if (!heldMk3) { b.filterForceExpand = true; safe(() => api.ui.overlays.update("hotbar")); }
		heldMk3 = a; return;
	}
	if (heldMk3 && a === "filterRightMk2" && mk3InHandBySource()) {
		b.activeStructureType = heldMk3;
		const CID = safe(() => sandkit.enums.ComponentId) || {};
		if (CID.Hotbar !== undefined) safe(() => api.ui.update(CID.Hotbar));
		safe(() => api.ui.overlays.update("hotbar"));
		return;
	}
	heldMk3 = null;
}));
// saves that researched the node before the building existed: unlock it now
setInterval(() => {
	if (!mk3Ready || !isEnabled() || !inGame()) return;
	const done = safe(() => api.tech.isResearchedById(TECH_FILTER_MK3));
	const have = safe(() => sandkit.state.store.player.buildings);
	if (done === true && Array.isArray(have) && have.indexOf(MK3_R) === -1) safe(() => api.player.buildings.unlockById(MK3_R));
}, 2000);

// Filter Mk.3 - under Manufacturing, beside Glass. Also needs Advanced Filters
// (the vanilla research that unlocks the Mk.2 Filter), looked up by enum name. Without
// that gate the node is not registered at all: the vertical variant is the vanilla Mk.2
// filter wall, which the node would otherwise unlock before Advanced Filters.
{
	const adv = safe(() => sandkit.enums.Tech.AdvancedFilters);
	if (adv === undefined || adv === null) console.error(`[${MOD_ID}] Filter Mk.3 research node NOT registered: sandkit.enums.Tech.AdvancedFilters is missing (the Advanced Filters gate cannot be resolved)`);
	else if (safe(() => api.tech.getDefinitionById(TECH_MANU)) && !safe(() => api.tech.getDefinitionById(TECH_FILTER_MK3))) {
		const definition = {
			nameKey: `tech|${TECH_FILTER_MK3}|name`,
			descriptionKey: `tech|${TECH_FILTER_MK3}|description`,
			cost: FILTER_MK3_COST,
			currencyType: "gold",
			branch: "heat",
			requires: [TECH_MANU, adv],
			unlocks: mk3Ready ? { structures: [MK3_R] } : {},
		};
		let done = false;
		for (const preferredPosition of [{ row: 15, col: 0 }, { row: 14, col: 1 }, { row: 15, col: 1 }, { row: 16, col: 0 }, null]) {
			try {
				api.tech.registerNode(TECH_FILTER_MK3, definition,
					preferredPosition ? { parentId: TECH_MANU, preferredPosition } : { parentId: TECH_MANU });
				console.log(`[${MOD_ID}] research node registered: Filter Mk.3 (under Manufacturing)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Filter Mk.3 node could not be placed`);
	}
}


// ------------------------------------------------- Mod Tools: red-block fix --
// Stuck "red blocks" are orphaned Block terrain (built-in cell type): the engine stamps
// Block under every structure, and a structure removed through a path that never
// un-stamped it leaves that terrain behind as bare, undiggable red blocks with
// nothing on top to deconstruct. Real Block cells always have their structure
// sitting on them, so the rule is: clear only Block cells with NO structure.
// (Block terrain is never used for the map border, so the sweep can't hurt the
// world edges.) Uses the engine's own force-remove-terrain excavate.
//
// Trigger: the "Clear stuck red blocks" setting. Mods can read settings but not
// write them, so it's edge-triggered — flipping it ON runs one sweep; to run
// again, flip it OFF and back ON.
//
// Every terrain id the sweep matches is resolved BY NAME at runtime
// (terrains.getTypeById also knows the built-in cell types, case-insensitively).
// Terrain numbers past the built-ins are handed out in registration order, so a
// hard-coded number can be real terrain in another world or mod set and would be
// wiped map-wide. A name that doesn't resolve is not swept; if Block itself
// can't be resolved the sweep refuses to run. (Undamaged terrain's cell id IS
// its terrain type, so getCellIdAtCell compares directly.)
const BLOCK_NAME = "block";
// Extra stamp terrains to treat like Block, by terrain id. 0.11.0 also swept a
// raw id 56 (a mod-structure stamp in one save, name never recorded) - if that
// is needed again, read its name off the cell probe and add it here.
const STAMP_NAMES = ["modStructure", "mod_structure"];
function terrainByName(n) { const t = safe(() => api.terrains.getTypeById(n)); return typeof t === "number" && t > 0 ? t : null; }
function stampSet() {
	const block = terrainByName(BLOCK_NAME);
	if (block === null) return null;
	const ids = new Set([block]);
	for (const n of STAMP_NAMES) { const t = terrainByName(n); if (t !== null) ids.add(t); }
	return ids;
}
let _rbFix = null, _rbLastFlag = null;
function startRedBlockSweep() {
	if (!isEnabled()) return;
	const d = safe(() => api.world && api.world.getDimensions()) || {};
	const W = d.widthCells | 0, H = d.heightCells | 0;
	if (W <= 0 || H <= 0) { safe(() => api.ui.toast("Red-block fix: world not ready")); return; }
	const ids = stampSet();
	if (!ids) {
		safe(() => api.ui.toast("Red-block fix: can't identify Block terrain by name - nothing swept"));
		console.error(`[${MOD_ID}] red-block sweep refused: terrain "${BLOCK_NAME}" did not resolve`);
		return;
	}
	_rbFix = { W, total: W * H, cursor: 0, found: 0, cleared: 0, budget: 25000, nextToastPct: 25, ids };
	safe(() => api.ui.toast("Clearing stuck red blocks... scanning the whole map (~30s)"));
	console.log(`[${MOD_ID}] red-block sweep started: ${W}x${H}`);
}
setInterval(() => {
	if (!_rbFix || !inGame()) return;
	if (!isEnabled()) { console.log(`[${MOD_ID}] red-block sweep cancelled: mod disabled`); _rbFix = null; return; }
	const f = _rbFix, world = api.world, structs = api.structures;
	let n = 0;
	try {
		while (f.cursor < f.total && n < f.budget) {
			const x = f.cursor % f.W, y = (f.cursor / f.W) | 0;
			if (f.ids.has(world.getCellIdAtCell(x, y))) {
				f.found++;
				if (!structs.getAtCell(x, y)) { world.excavateAtCell(x, y, { x: 0, y: 0 }, 1, { forceRemoveAll: true }); f.cleared++; }
			}
			f.cursor++; n++;
		}
	} catch (e) { f.cursor++; }
	const pct = Math.floor((100 * f.cursor) / f.total);
	if (pct >= f.nextToastPct && f.cursor < f.total) { safe(() => api.ui.toast(`Red-block fix: ${pct}%`)); f.nextToastPct += 25; }
	if (f.cursor >= f.total) {
		const kept = f.found - f.cleared;
		safe(() => api.ui.toast(`Red-block fix done: cleared ${f.cleared} stuck cells (${kept} real ones kept)`));
		console.log(`[${MOD_ID}] red-block sweep done: cleared ${f.cleared}, kept ${kept}`);
		_rbFix = null;
	}
}, 50);
// edge-trigger on the setting: react instantly via onChange, with a poll as backup
function checkRedBlockFlag() {
	const on = !!setting("clearRedBlocks", false);
	if (_rbLastFlag === null) { _rbLastFlag = on; return; }   // don't fire on the value we booted with
	if (on && !_rbLastFlag && !_rbFix) startRedBlockSweep();
	_rbLastFlag = on;
}
safe(() => api.settings.onChange(checkRedBlockFlag));
setInterval(checkRedBlockFlag, 1000);

// -------------------------------------------- Mod Tools: cell probe (debug) --
// Turn on "Show cell probe" in settings to get a small HUD that reports what is
// at your cell and in a 5x5 around your feet: structure type, element name,
// terrain + raw cell id. Reports EVERY layer at a cell so overlapping things
// can't mask each other. Use it to identify mystery blocks.
function probeName(t) { return safe(() => api.elements.getNameByType(t)) || ("type " + t); }
function probeCell(x, y) {
	const parts = [];
	const st = safe(() => api.structures.getAtCell(x, y));
	if (st && st.type !== undefined && st.type !== null) parts.push("struct " + String(st.type));
	const et = safe(() => api.elements.getResolvedTypeAtCell(x, y));
	if (et !== null && et !== undefined) parts.push("elem " + probeName(et));
	const id = safe(() => api.world && api.world.getCellIdAtCell(x, y));
	const ter = safe(() => api.world && api.world.isTerrainAtCell(x, y));
	if (ter) { const def = safe(() => api.terrains.getDefinitionByType(id)); const nm = def && (def.id || def.name || def.nameKey); parts.push("TERRAIN id " + id + (nm ? " (" + nm + ")" : "")); }
	else if (typeof id === "number" && id !== 0 && (et === null || et === undefined)) parts.push("cellId " + id);
	if (!parts.length) return (typeof id === "number" && id !== 0) ? ("cellId " + id) : "empty";
	return parts.join(" + ");
}
function probeArea(cx, cy, r) {
	const out = [];
	for (let dy = -r; dy <= r; dy++) for (let dx = -r; dx <= r; dx++) {
		const d = probeCell(cx + dx, cy + dy);
		if (d !== "empty") out.push((dx >= 0 ? "+" : "") + dx + "," + (dy >= 0 ? "+" : "") + dy + ": " + d);
	}
	return out;
}
if (ReactM && hM) {
	function CellProbe() {
		const [, bump] = ReactM.useState(0);
		ReactM.useEffect(() => { const id = setInterval(() => bump((v) => v + 1), 400); return () => clearInterval(id); }, []);
		if (!isEnabled() || !inGame() || !setting("showProbe", false)) return null;
		const p = safe(() => api.player && api.player.getWorldPosition());
		if (!p || typeof p.x !== "number") return null;
		const CS = 4;
		const cx = Math.floor((p.x + 6) / CS), cy = Math.floor((p.y + 15) / CS), fy = Math.floor((p.y + 31) / CS);
		const near = probeArea(cx, fy, 2);
		const line = (label, txt) => hM("div", null, hM("span", { style: { color: "#f0a080" } }, label + " "), txt);
		return hM("div", {
			style: { position: "fixed", right: "12px", top: "84px", zIndex: 99997, pointerEvents: "none", maxWidth: "340px",
				padding: "7px 9px", background: "rgba(12,12,18,0.9)", border: "1px solid rgba(235,90,60,0.55)", borderRadius: "6px",
				font: "10.5px monospace", color: "#ddd", lineHeight: 1.45, whiteSpace: "pre-wrap" },
		},
			hM("div", { style: { fontWeight: 700, color: "#f0a080", marginBottom: "3px" } }, "CELL PROBE  (Mod Tools)"),
			line("Here", "cell " + cx + "," + cy + " -> " + probeCell(cx, cy)),
			line("Under feet", "cell " + cx + "," + fy + " -> " + probeCell(cx, fy)),
			hM("div", { style: { color: "#f0a080", marginTop: "3px" } }, "Nearby 5x5 around feet (offset: what)"),
			hM("div", { style: { maxHeight: "150px", overflow: "hidden" } }, near.length ? near.join("\n") : "all empty"));
	}
	safe(() => api.ui.inject("brandon-cell-probe", CellProbe));
}
}
// Hot-load. main.real.js is read from THIS mod's own folder (the game resolves
// it via api.assets.getUrl, so any install path works), and the worker is told
// the same folder through the "hotloadUrl" shared buffer. The baked copy above
// runs only if the file can't be read or doesn't compile - never after the real
// code has started (its registrations would happen twice). The game awaits this
// entry, so the real code is awaited too and its errors reach the game.
await (async function () {
	var src = null, fn = null;
	try {
		var wu = sandkit.api.assets.getUrl("worker.real.js"), wb = sandkit.api.shared.buffers.create("hotloadUrl", { type: "uint16", length: 1024 });
		if (wu.length < wb.length) for (var i = 0; i < wu.length; i++) wb[i] = wu.charCodeAt(i);
	} catch (e) {}
	try {
		var xhr = new XMLHttpRequest();
		xhr.open("GET", sandkit.api.assets.getUrl("main.real.js") + "?ts=" + Date.now(), false);
		xhr.send();
		if (xhr.status === 0 || xhr.status === 200) src = xhr.responseText;
	} catch (e) { src = null; }
	if (src) {
		try { fn = new (Object.getPrototypeOf(async function(){}).constructor)("sandkit", "\"use strict\";\n" + src); }
		catch (e) { console.warn("[brandon.manufacturing] main.real.js failed to compile, using baked:", e && e.message); }
	}
	if (fn) { await fn(sandkit); console.log("[brandon.manufacturing] main.js hot-loaded fresh from disk"); }
	else { await __baked(sandkit); if (!src) console.log("[brandon.manufacturing] main.js using baked code (no disk read)"); }
})();
