// Glass Sand - generated by Sandustry Material Studio on 2026-09-07.
// Compiled from the studio graph: 2 materials, 1 recipes, 0 touch reactions.

const api = sandkit.api;
const MOD_ID = "brandon.glasssand";

function setting(key, fallback) {
	try { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }
}
const isEnabled = () => setting("enabled", true);
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }

// ------------------------------------------------------------ elements --
// NEVER reorder this list; append only. Element type ids are assigned in
// registration order and a save remembers them by number.
const ELEMENTS = [
	{
		"id": "Glasssand",
		"name": "Glass sand",
		"matter": "Solid",
		"density": 150,
		"metaColor": 15132390,
		"colors": [
			[
				230,
				230,
				230,
				255
			],
			[
				207,
				207,
				207,
				255
			],
			[
				255,
				255,
				255,
				255
			],
			[
				184,
				184,
				184,
				255
			]
		]
	},
	{
		"id": "glass",
		"name": "glass",
		"matter": "Solid",
		"density": 140,
		"metaColor": 11842220,
		"colors": [
			[
				180,
				178,
				172,
				255
			],
			[
				162,
				160,
				155,
				255
			],
			[
				202,
				199,
				193,
				255
			],
			[
				144,
				142,
				138,
				255
			]
		]
	}
];

const MatterType = safe(() => sandkit.enums.MatterType) || {};
const typeById = new Map();
for (const e of ELEMENTS) {
	const matterType = MatterType[e.matter];
	if (typeof matterType !== "number") { console.error(`[${MOD_ID}] unknown matter type "${e.matter}" for "${e.id}"`); continue; }
	try {
		const def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };
		if (e.fl && e.fl.grabbable === false) def.grabbable = false;
		if (e.fl && e.fl.transportable === false) def.isTransportable = false;
		const r = api.elements.register(def);
		if (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);
		console.log(`[${MOD_ID}] element registered: ${e.id} -> type ${r && r.elementType}`);
	} catch (err) { console.error(`[${MOD_ID}] element "${e.id}" failed to register:`, err); }
}
// Vanilla element types the recipes and reactions reference.
for (const id of []) {
	const t = safe(() => api.elements.getTypeFromId(id));
	if (typeof t === "number") typeById.set(id, t);
	else console.error(`[${MOD_ID}] vanilla element "${id}" not found`);
}
const typeOf = (id) => typeById.get(id);

// ------------------------------------------------------------- recipes --
// One recipe per input per machine is the engine's rule.
if (isEnabled()) {
	{
		const input = typeOf("Glasssand"), output = typeOf("glass");
		if (input !== undefined && output !== undefined) {
			try {
				api.structures.recipes.register("smelter", { input, outputs: [{ elementType: output, chance: 1 }] });
				console.log(`[${MOD_ID}] Smelter recipe: Glasssand -> glass`);
			} catch (e) { console.error(`[${MOD_ID}] recipe Glasssand -> glass failed:`, e); }
		}
	}
}

// -------------------------------------------------------------- tooltips --
safe(() => api.elements.addInteractionInfo("Glasssand", { kind: "custom", text: "Smelter: Glasssand → glass" }));

console.log(`[${MOD_ID}] loaded`);
