// Glass Sand - generated by Sandustry Material Studio on 2026-09-07.
// Compiled from the studio graph: 3 materials, 1 recipes, 1 touch reactions.

const api = sandkit.api;
const MOD_ID = "brandon.glasssand";

function setting(key, fallback) {
	try { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }
}
const isEnabled = () => setting("enabled", true);
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }

// ------------------------------------------------------------ elements --
// NEVER reorder this list; append only. Element type ids are assigned in
// registration order and a save remembers them by number.
const ELEMENTS = [
	{
		"id": "Soil",
		"name": "Soil",
		"matter": "Solid",
		"density": 150,
		"metaColor": 3875345,
		"colors": [
			[
				59,
				34,
				17,
				255
			],
			[
				53,
				31,
				15,
				255
			],
			[
				66,
				38,
				19,
				255
			],
			[
				47,
				27,
				14,
				255
			]
		]
	},
	{
		"id": "WetSoil",
		"name": "Wet Soil",
		"matter": "Slushy",
		"density": 150,
		"metaColor": 8018492,
		"colors": [
			[
				122,
				90,
				60,
				255
			],
			[
				110,
				81,
				54,
				255
			],
			[
				137,
				101,
				67,
				255
			],
			[
				98,
				72,
				48,
				255
			]
		]
	},
	{
		"id": "glass",
		"name": "glass",
		"matter": "Solid",
		"density": 140,
		"metaColor": 11842220,
		"colors": [
			[
				180,
				178,
				172,
				255
			],
			[
				162,
				160,
				155,
				255
			],
			[
				202,
				199,
				193,
				255
			],
			[
				144,
				142,
				138,
				255
			]
		]
	}
];

const MatterType = safe(() => sandkit.enums.MatterType) || {};
const typeById = new Map();
for (const e of ELEMENTS) {
	const matterType = MatterType[e.matter];
	if (typeof matterType !== "number") { console.error(`[${MOD_ID}] unknown matter type "${e.matter}" for "${e.id}"`); continue; }
	try {
		const def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };
		if (e.fl && e.fl.grabbable === false) def.grabbable = false;
		if (e.fl && e.fl.transportable === false) def.isTransportable = false;
		const r = api.elements.register(def);
		if (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);
		console.log(`[${MOD_ID}] element registered: ${e.id} -> type ${r && r.elementType}`);
	} catch (err) { console.error(`[${MOD_ID}] element "${e.id}" failed to register:`, err); }
}
// Vanilla element types the recipes and reactions reference.
for (const id of ["sand","gold","residue","water","wetSand"]) {
	const t = safe(() => api.elements.getTypeFromId(id));
	if (typeof t === "number") typeById.set(id, t);
	else console.error(`[${MOD_ID}] vanilla element "${id}" not found`);
}
const typeOf = (id) => typeById.get(id);

// ------------------------------------------------------------- recipes --
// One recipe per input per machine is the engine's rule.
if (isEnabled()) {
	{
		const input = typeOf("sand"), output = typeOf("glass");
		if (input !== undefined && output !== undefined) {
			try {
				api.structures.recipes.register("smelter", { input, outputs: [{ elementType: output, chance: 1 }] });
				console.log(`[${MOD_ID}] Smelter recipe: sand -> glass`);
			} catch (e) { console.error(`[${MOD_ID}] recipe sand -> glass failed:`, e); }
		}
	}
}

// -------------------------------------------------------------- tooltips --
safe(() => api.elements.addInteractionInfo("sand", { kind: "custom", text: "Smelter: sand → glass" }));

// ------------------------------------------------------ shaker recipes --
// Engine shape: one recipe per input; outputsBelow drop out the bottom
// (vanilla: gold), outputsAbove are thrown out the top (vanilla: residue).
if (isEnabled()) {
	{
		const input = typeOf("WetSoil");
		const below = ["gold"].map(typeOf), above = ["residue"].map(typeOf);
		if (input !== undefined && below.concat(above).every(t => t !== undefined)) {
			try {
				api.structures.recipes.register("shaker", {
					input,
					outputsBelow: below.map(t => ({ elementType: t, chance: 0.5 })),
					outputsAbove: above.map(t => ({ elementType: t, chance: 0.5 })),
				});
				console.log(`[${MOD_ID}] shaker recipe: WetSoil -> gold below / residue above`);
			} catch (e) { console.error(`[${MOD_ID}] shaker recipe WetSoil failed:`, e); }
		}
	}
}

// ------------------------------------------- shared state for the worker --
let shared = null;
try { shared = api.shared.buffers.create("state", { type: "uint32", length: 13 }); } catch (e) { console.error(`[${MOD_ID}] shared buffer failed:`, e); }
function publish() {
	if (!shared) return;
	shared[0] = isEnabled() ? 1 : 0;
	shared[8] = typeOf("Soil") || 0;
	shared[9] = typeOf("water") || 0;
	shared[10] = typeOf("WetSoil") || 0;
	shared[11] = typeOf("wetSand") || 0;
	shared[12] = typeOf("sand") || 0;
}
publish(); setInterval(publish, 1000);

console.log(`[${MOD_ID}] loaded`);
