// Glass Sand - generated by Sandustry Material Studio on 2026-09-07.
// Compiled from the studio graph: 2 materials, 1 recipes, 0 touch reactions.

const api = sandkit.api;
const MOD_ID = "brandon.glasssand";

function setting(key, fallback) {
	try { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }
}
const isEnabled = () => setting("enabled", true);
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }

// ------------------------------------------------------------ elements --
// NEVER reorder this list; append only. Element type ids are assigned in
// registration order and a save remembers them by number.
const ELEMENTS = [
	{
		"id": "glassSand",
		"name": "Glass Sand",
		"matter": "Solid",
		"density": 150,
		"metaColor": 15132390,
		"colors": [
			[
				230,
				230,
				230,
				255
			],
			[
				207,
				207,
				207,
				255
			],
			[
				255,
				255,
				255,
				255
			],
			[
				184,
				184,
				184,
				255
			]
		]
	},
	{
		"id": "glass",
		"name": "glass",
		"matter": "Solid",
		"density": 140,
		"metaColor": 11842220,
		"colors": [
			[
				180,
				178,
				172,
				255
			],
			[
				162,
				160,
				155,
				255
			],
			[
				202,
				199,
				193,
				255
			],
			[
				144,
				142,
				138,
				255
			]
		]
	}
];

const MatterType = safe(() => sandkit.enums.MatterType) || {};
const typeById = new Map();
for (const e of ELEMENTS) {
	const matterType = MatterType[e.matter];
	if (typeof matterType !== "number") { console.error(`[${MOD_ID}] unknown matter type "${e.matter}" for "${e.id}"`); continue; }
	try {
		const def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };
		if (e.fl && e.fl.grabbable === false) def.grabbable = false;
		if (e.fl && e.fl.transportable === false) def.isTransportable = false;
		const r = api.elements.register(def);
		if (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);
		console.log(`[${MOD_ID}] element registered: ${e.id} -> type ${r && r.elementType}`);
	} catch (err) { console.error(`[${MOD_ID}] element "${e.id}" failed to register:`, err); }
}
// Vanilla element types the recipes and reactions reference.
for (const id of ["sand","wetSand"]) {
	const t = safe(() => api.elements.getTypeFromId(id));
	if (typeof t === "number") typeById.set(id, t);
	else console.error(`[${MOD_ID}] vanilla element "${id}" not found`);
}
const typeOf = (id) => typeById.get(id);

// ------------------------------------------------------------- recipes --
// One recipe per input per machine is the engine's rule.
if (isEnabled()) {
	{
		const input = typeOf("glassSand"), output = typeOf("glass");
		if (input !== undefined && output !== undefined) {
			try {
				api.structures.recipes.register("smelter", { input, outputs: [{ elementType: output, chance: 1 }] });
				console.log(`[${MOD_ID}] Smelter recipe: glassSand -> glass`);
			} catch (e) { console.error(`[${MOD_ID}] recipe glassSand -> glass failed:`, e); }
		}
	}
}

// -------------------------------------------------------------- tooltips --
safe(() => api.elements.addInteractionInfo("glassSand", { kind: "custom", text: "Smelter: glassSand → glass" }));

// -------------------------------------------- vanilla element makeovers --
// updateDefinition on a LIVE element type Object.assigns into the engine's
// definition table and broadcasts to every sim worker - all existing grains
// change identity instantly. nameKey must be cleared or i18n wins the name.
if (isEnabled()) {
	{
		const t = typeOf("sand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "Soil", metaColor: 3875345, colors: { variants: [[59,34,17,255],[53,31,15,255],[66,38,19,255],[47,27,14,255]] } }));
			console.log(`[${MOD_ID}] vanilla makeover applied: sand -> "Soil"`);
		}
	}
	{
		const t = typeOf("wetSand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "Wet Soil", metaColor: 8018492, colors: { variants: [[122,90,60,255],[110,81,54,255],[137,101,67,255],[98,72,48,255]] } }));
			console.log(`[${MOD_ID}] vanilla makeover applied: wetSand -> "Wet Soil"`);
		}
	}
}

// ---------------------------------------------- terrain output swaps --
// The Glassworks v0.10 pattern: terrains.updateDefinition replaces what a
// broken terrain cell spawns, live, across all sim threads.
if (isEnabled()) {
	{
		const out = typeOf("glassSand");
		if (typeof out === "number") {
			const ok = safe(() => (api.terrains.updateDefinition("dune", { output: { elementType: out, chance: 1 } }), true));
			if (ok) console.log(`[${MOD_ID}] dune now drops glassSand`);
			else console.error(`[${MOD_ID}] dune output swap failed`);
		}
	}
}

console.log(`[${MOD_ID}] loaded`);
