// Manufacturing - generated by Sandustry Material Studio on 2026-09-12.
// Compiled from the studio graph: 2 materials, 0 recipes, 0 touch reactions.

const api = sandkit.api;
const MOD_ID = "brandon.manufacturing";

function setting(key, fallback) {
	try { const v = api.settings.get(key); return v === undefined || v === null ? fallback : v; } catch (e) { return fallback; }
}
const isEnabled = () => setting("enabled", true);
function safe(fn) { try { return fn(); } catch (e) { return undefined; } }

// ------------------------------------------------------------ elements --
// NEVER reorder this list; append only. Element type ids are assigned in
// registration order and a save remembers them by number.
const ELEMENTS = [
	{
		"id": "glass",
		"name": "Glass",
		"matter": "Solid",
		"density": 140,
		"metaColor": 11842220,
		"colors": [
			[
				180,
				178,
				172,
				255
			],
			[
				162,
				160,
				155,
				255
			],
			[
				202,
				199,
				193,
				255
			],
			[
				144,
				142,
				138,
				255
			]
		]
	},
	{
		"id": "Sand",
		"name": "Sand",
		"matter": "Solid",
		"density": 150,
		"metaColor": 16766814,
		"colors": [
			[
				255,
				215,
				94,
				255
			],
			[
				230,
				194,
				85,
				255
			],
			[
				255,
				241,
				105,
				255
			],
			[
				204,
				172,
				75,
				255
			]
		]
	}
];

const MatterType = safe(() => sandkit.enums.MatterType) || {};
const typeById = new Map();
for (const e of ELEMENTS) {
	const matterType = MatterType[e.matter];
	if (typeof matterType !== "number") { console.error(`[${MOD_ID}] unknown matter type "${e.matter}" for "${e.id}"`); continue; }
	try {
		const def = { id: e.id, name: e.name, matterType, density: e.density, metaColor: e.metaColor, colors: { variants: e.colors } };
		// The game's own mod elements ALWAYS declare these explicitly - paths
		// like the grabber's release branch on them, and undefined lands wrong
		// (held grains render red, released grains never rejoin the sim).
		def.isGrabbable = !(e.fl && e.fl.grabbable === false);
		def.isTransportable = !(e.fl && e.fl.transportable === false);
		if (e.fl && e.fl.grabbable === false) def.grabbable = false;
		const r = api.elements.register(def);
		if (r && typeof r.elementType === "number") typeById.set(e.id, r.elementType);
		console.log(`[${MOD_ID}] element registered: ${e.id} -> type ${r && r.elementType}`);
	} catch (err) { console.error(`[${MOD_ID}] element "${e.id}" failed to register:`, err); }
}
// Vanilla element types the recipes and reactions reference.
for (const id of ["sunsand","sand","wetSand"]) {
	const t = safe(() => api.elements.getTypeFromId(id));
	if (typeof t === "number") typeById.set(id, t);
	else console.error(`[${MOD_ID}] vanilla element "${id}" not found`);
}
const typeOf = (id) => typeById.get(id);


// -------------------------------------------- vanilla element makeovers --
// updateDefinition on a LIVE element type Object.assigns into the engine's
// definition table and broadcasts to every sim/render worker. The catch:
// at mod-load time the worker pool does not exist yet, so a single early
// call updates only the main thread (names, tooltips) and the COLOR change
// never reaches the renderer. Re-applying on a schedule catches the workers
// once they spawn - the call is idempotent, and the renderer reads the
// scheme live, so every existing grain recolors the moment it lands.
function applyMakeovers() {
	if (!isEnabled()) return;
	{
		const t = typeOf("sand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "soil" }));
		}
	}
	{
		const t = typeOf("wetSand");
		if (typeof t === "number") {
			safe(() => api.elements.updateDefinition(t, { nameKey: void 0, name: "Wet Soil" }));
		}
	}
	console.log(`[${MOD_ID}] vanilla makeovers applied (sand, wetSand)`);
}
applyMakeovers();
// Event-driven, not polled: the game emits "game:ready" when a world
// session is fully initialized (its own internal mods hook the same
// event for world-init work). Apply once there, plus one safety pass.
safe(() => api.events.on("game:ready", () => safe(applyMakeovers)));
setTimeout(applyMakeovers, 4000);

// ---------------------------------------------- terrain output swaps --
// The Glassworks v0.10 pattern: terrains.updateDefinition replaces what a
// broken terrain cell spawns, live, across all sim threads.
if (isEnabled()) {
	{
		const out = typeOf("Sand");
		if (typeof out === "number") {
			const ok = safe(() => (api.terrains.updateDefinition("dune", { output: { elementType: out, chance: 1 } }), true));
			if (ok) console.log(`[${MOD_ID}] dune now drops Sand`);
			else console.error(`[${MOD_ID}] dune output swap failed`);
		}
	}
}

// ------------------------------------------- shared state for the worker --
let shared = null;
try { shared = api.shared.buffers.create("state", { type: "uint32", length: 10 }); } catch (e) { console.error(`[${MOD_ID}] shared buffer failed:`, e); }
function publish() {
	if (!shared) return;
	shared[0] = isEnabled() ? 1 : 0;
	shared[8] = typeOf("sunsand") || 0;
	shared[9] = typeOf("Sand") || 0;
}
publish(); setInterval(publish, 1000);

// Version banner: toast once when the player is actually in the world -
// the visible proof of exactly which build is running.
{
	let bannered = false;
	const bannerTimer = setInterval(() => {
		if (bannered) return clearInterval(bannerTimer);
		const active = safe(() => api.scene.getActive());
		const Scene = safe(() => sandkit.enums.Scene) || {};
		const menus = [Scene.MainMenu, Scene.Intro].filter(v => typeof v === "number");
		const inWorld = active !== undefined && active !== null && (menus.length ? !menus.includes(active) : active > 2);
		if (!inWorld) return;
		bannered = true;
		safe(() => api.ui.toast("Manufacturing v0.8.1 running"));
	}, 800);
}
console.log(`[${MOD_ID}] loaded`);


// =========================================================================
// MOD TOOLS (testing) - ported from Glassworks, combined into ONE upgrade.
//
// A single free research node, "Mod Tools", hangs off the Shaker (the first
// node at the top of the tree). Researching it unlocks everything at once:
//   - the Matter Gun: a real hotbar item that fires any material; a picker
//     bar appears at the bottom of the screen while it is in hand
//   - vacuum tank delete buttons: a small x on every tank in the Tanks box
//   - the Omni Vacuum: sucks ANY material (liquids, gases, statics, the
//     untransportable - never structures) and multiplies tank storage x10,
//     with the % readout rescaled to the big capacity
// =========================================================================

function inGame() {
	const active = safe(() => api.scene.getActive());
	if (active === undefined || active === null) return true;
	const Scene = safe(() => sandkit.enums.Scene) || {};
	const menus = [Scene.MainMenu, Scene.Intro].filter((v) => typeof v === "number");
	if (menus.length > 0) return !menus.includes(active);
	return active !== 1 && active !== 2;
}

const TECH_TOOLS = "brandonModTools";
const toolsUnlocked = () => safe(() => api.tech.isLockedById(TECH_TOOLS)) === false;

// --- the Matter Gun ---
const GUN = "brandonMatterGun";
const AS = safe(() => sandkit.enums.ActionState) || { Start: 1, Active: 2, End: 3 };
const ReactM = safe(() => sandkit.react);
const hM = ReactM ? ReactM.createElement : null;

let gunPalette = [];
let gunType = null;
function buildGunPalette() {
	const types = safe(() => api.elements.getRegisteredTypes(), []) || [];
	const MT = safe(() => sandkit.enums.MatterType) || {};
	gunPalette = types
		.map((type) => {
			const def = safe(() => api.elements.getDefinitionByType(type)) || {};
			const metaColor = typeof def.metaColor === "number" ? def.metaColor : null;
			return {
				type,
				name: safe(() => api.elements.getNameByType(type), null) || `type ${type}`,
				matterType: def.matterType,
				color: metaColor === null ? "#8a8a8a" : `#${metaColor.toString(16).padStart(6, "0")}`,
			};
		})
		.filter((p) => p.matterType !== (safe(() => sandkit.enums.MatterType.Particle)))
		.sort((a, b) => a.name.localeCompare(b.name));
	if (gunType === null && gunPalette.length > 0) gunType = gunPalette[0].type;
}
buildGunPalette();
setTimeout(buildGunPalette, 3000); // catch late registrations

try {
	await api.sprites.loadFromMod(GUN, "matter_gun.png");
	await api.sprites.loadFromMod(`${GUN}Icon`, "matter_gun_icon.png");
} catch (e) {
	console.error(`[${MOD_ID}] matter gun sprites failed to load:`, e);
}

try {
	api.items.register({
		id: GUN,
		name: "Matter Gun",
		description: "A testing tool that fires any material in the game. Select it and a picker appears at the bottom of the screen - click a swatch to choose what it spews, then hold to spray at the cursor.",
		categoryKey: "utility",
		sprite: { id: GUN, type: "twohand", ui: { imageName: `${GUN}Icon` } },
		handleAction: (e, t) => safe(() => {
			if (!isEnabled()) return;
			if (!e.session.action.state[AS.Active]) return;
			const cell = safe(() => api.input.getMouseCellPosition());
			if (!cell || gunType === null) return;
			safe(() => api.grid.forEachCellInCircle(cell.x, cell.y, 2, (x, y) => {
				safe(() => api.elements.createAtCellWhenIdle(x, y, gunType));
			}));
		}),
	});
	console.log(`[${MOD_ID}] Matter Gun registered`);
} catch (e) {
	console.error(`[${MOD_ID}] Matter Gun registration failed:`, e);
}

function gunInHand() {
	const act = safe(() => api.action.getActive());
	return !!act && typeof act === "object" && String(act.id) === GUN;
}

if (ReactM && hM) {
	function MatterGunPicker() {
		const [, bump] = ReactM.useState(0);
		ReactM.useEffect(() => {
			const id = setInterval(() => bump((v) => v + 1), 150);
			return () => clearInterval(id);
		}, []);
		if (!isEnabled() || !inGame() || !gunInHand()) return null;
		if (gunPalette.length === 0) buildGunPalette();
		return hM("div", {
			style: {
				position: "fixed", left: "50%", bottom: "86px", transform: "translateX(-50%)",
				display: "flex", flexWrap: "wrap", justifyContent: "center", gap: "4px",
				maxWidth: "640px", maxHeight: "96px", overflowY: "auto",
				padding: "6px 8px", background: "rgba(12, 12, 18, 0.88)",
				border: "1px solid rgba(235, 90, 60, 0.55)", borderRadius: "6px",
				zIndex: 1000, pointerEvents: "auto",
				font: "11px monospace", color: "#ddd",
			},
		},
			gunPalette.map((p) =>
				hM("button", {
					key: p.type,
					onClick: () => { gunType = p.type; safe(() => api.ui.toast(`Matter Gun: ${p.name}`)); },
					style: {
						display: "flex", alignItems: "center", gap: "4px",
						padding: "2px 6px", cursor: "pointer", font: "inherit",
						background: gunType === p.type ? "rgba(235, 90, 60, 0.25)" : "rgba(255,255,255,0.06)",
						border: `1px solid ${gunType === p.type ? "rgba(235,90,60,0.9)" : "transparent"}`,
						borderRadius: "3px", color: gunType === p.type ? "#f0a080" : "#ccc",
					},
				},
					hM("span", { style: {
						width: "10px", height: "10px", background: p.color,
						borderRadius: "2px", border: "1px solid rgba(0,0,0,0.6)", flexShrink: 0,
					} }),
					p.name
				)
			)
		);
	}
	safe(() => api.ui.inject("matter-gun-picker", MatterGunPicker)) ||
		console.warn(`[${MOD_ID}] picker injection failed`);
}

// --- vacuum tools: tank delete buttons + omni-suck, gated on the same node ---
const ItemTypeE = safe(() => sandkit.enums.ItemType) || {};
const ItemIdE = safe(() => sandkit.enums.ItemId) || {};

function vacuumItem() {
	const inv = safe(() => sandkit.state.store.player.inventory);
	if (!Array.isArray(inv)) return null;
	return inv.find((it) => it && it.itemType === ItemTypeE.Tool && it.id === ItemIdE.Vacuum) || null;
}
function vacuumInHand() {
	const act = safe(() => api.action.getActive());
	return !!act && typeof act === "object" && act.id === ItemIdE.Vacuum;
}
const omniUnlocked = toolsUnlocked; // one node rules them all
const refreshHotbar = () => safe(() => api.ui.overlays.update("hotbar"));
const VAC_CAPS = [500, 1000, 1500, 2000, 2500, 3000];
function vacuumCap() {
	const lvl = safe(() => api.upgrades.getLevelById("vacuum", "capacity"), 0) || 0;
	return VAC_CAPS[Math.max(0, Math.min(VAC_CAPS.length - 1, lvl))];
}
const omniCap = () => vacuumCap() * 10;

function tanksSectionRow() {
	const label = safe(() => api.i18n.t("ui|vacuum|tanksSection"), null) || "Tanks";
	const spans = document.querySelectorAll("span");
	for (const span of spans) {
		if (span.textContent !== label) continue;
		const sib = span.nextElementSibling;
		const row = sib && sib.firstElementChild;
		if (row && row.children.length > 0) return { span, row };
	}
	return null;
}

function graftTankButtons() {
	if (!isEnabled() || !inGame() || !vacuumInHand()) return;
	if (!toolsUnlocked()) return; // whole toolkit sits behind the one node
	const item = vacuumItem();
	const tanks = item && item.data && Array.isArray(item.data.tanks) ? item.data.tanks : null;
	if (!tanks) return;
	const found = tanksSectionRow();
	if (!found) return;
	const { span, row } = found;
	if (omniUnlocked() && !span.querySelector(".gw-omni")) {
		const tag = document.createElement("span");
		tag.className = "gw-omni";
		tag.textContent = " OMNI";
		tag.style.cssText = "color:#8fd0ff;font-size:9px;margin-left:6px;letter-spacing:0.5px;";
		span.appendChild(tag);
	}
	const cells = row.children;
	if (omniUnlocked()) {
		const capX = omniCap();
		const pctOf = (amount) => (capX > 0 ? Math.min(100, Math.round((amount / capX) * 100)) : 0);
		const fixAll = (rootEl, pct) => {
			for (const el of rootEl.querySelectorAll("*")) {
				if (el.classList && el.classList.contains("gw-tank-x")) continue;
				if (el.style && typeof el.style.height === "string" && /%$/.test(el.style.height))
					el.style.height = pct + "%";
				if (el.children.length === 0 && /^\d{1,4}\s*%$/.test((el.textContent || "").trim()))
					el.textContent = pct + "%";
			}
		};
		for (let i = 0; i < cells.length && i < tanks.length; i++) {
			fixAll(cells[i], pctOf((tanks[i] && tanks[i].amount) || 0));
		}
		const rootBox = row.closest('[class*="inline-flex"]');
		if (rootBox) {
			const ai = typeof item.data.activeTankIdx === "number" ? item.data.activeTankIdx : 0;
			const at = tanks[Math.max(0, Math.min(tanks.length - 1, ai))];
			const pct = pctOf((at && at.amount) || 0);
			for (const el of rootBox.querySelectorAll("*")) {
				if (row.contains(el) || (el.classList && el.classList.contains("gw-tank-x"))) continue;
				if (el.children.length === 0 && /^\d{1,4}\s*%$/.test((el.textContent || "").trim()))
					el.textContent = pct + "%";
			}
		}
	}
	for (let i = 0; i < cells.length && i < tanks.length; i++) {
		const cell = cells[i];
		if (cell.querySelector(".gw-tank-x")) continue;
		if (!cell.style.position) cell.style.position = "relative";
		const btn = document.createElement("button");
		btn.className = "gw-tank-x";
		btn.type = "button";
		btn.textContent = "✕";
		btn.title = "Delete this tank's contents";
		btn.style.cssText =
			"position:absolute;top:-5px;right:-5px;width:13px;height:13px;line-height:11px;" +
			"padding:0;font-size:9px;text-align:center;cursor:pointer;z-index:5;" +
			"background:rgba(20,20,26,0.9);color:#f08080;border:1px solid rgba(235,60,60,0.7);" +
			"border-radius:50%;";
		const idx = i;
		btn.addEventListener("mousedown", (e) => { e.stopPropagation(); });
		btn.addEventListener("click", (e) => {
			e.stopPropagation();
			e.preventDefault();
			const it = vacuumItem();
			const ts = it && it.data && Array.isArray(it.data.tanks) ? it.data.tanks : null;
			if (ts && ts[idx]) {
				ts[idx].elementType = 0;
				ts[idx].amount = 0;
				refreshHotbar();
				safe(() => api.ui.toast(`Tank ${idx + 1} deleted`));
			}
		});
		cell.appendChild(btn);
	}
}
safe(() => setInterval(() => safe(graftTankButtons), 120));

let vacMouseDown = false;
safe(() => {
	window.addEventListener("mousedown", (e) => { if (e.button === 0) vacMouseDown = true; });
	window.addEventListener("mouseup", (e) => { if (e.button === 0) vacMouseDown = false; });
	window.addEventListener("blur", () => { vacMouseDown = false; });
});
let omniFrame = 0;
function omniSuck() {
	requestAnimationFrame(omniSuck);
	if (omniFrame++ % 3 !== 0) return;
	if (!isEnabled() || !vacMouseDown || !inGame()) return;
	if (!vacuumInHand() || !omniUnlocked()) return;
	const item = vacuumItem();
	const tanks = item && item.data && Array.isArray(item.data.tanks) ? item.data.tanks : null;
	if (!tanks) return;
	const cell = safe(() => api.input.getMouseCellPosition());
	if (!cell) return;
	const MT = safe(() => sandkit.enums.MatterType) || {};
	let collected = 0;
	safe(() => api.grid.forEachCellInCircle(cell.x, cell.y, 5, (x, y) => {
		if (collected >= 20) return;
		const info = safe(() => api.elements.getInfoAtCell(x, y));
		if (!info || typeof info.elementType !== "number" || info.elementType === 0) return;
		const def = safe(() => api.elements.getDefinitionByType(info.elementType)) || {};
		const blockedByVanilla =
			def.matterType === MT.Liquid || def.matterType === MT.Gas ||
			def.matterType === MT.Static || def.isTransportable === false;
		const base = vacuumCap(), max = base * 10;
		const floor = blockedByVanilla ? 0 : base;
		let tank = tanks.find((t) => t.elementType === info.elementType && t.amount >= floor && t.amount < max);
		if (!tank && blockedByVanilla) tank = tanks.find((t) => t.elementType === 0 || t.amount <= 0);
		if (!tank) return;
		if (tank.elementType !== info.elementType) { tank.elementType = info.elementType; tank.amount = Math.max(0, tank.amount); }
		tank.amount++;
		collected++;
		safe(() => api.elements.removeAtCellWhenIdle(x, y));
	}));
	if (collected > 0) refreshHotbar();
}
safe(() => requestAnimationFrame(omniSuck));

// --- the ONE free research node, behind the first node at the top (Shaker) ---
{
	const parent = safe(() => sandkit.enums.Tech.Shaker);
	if (parent !== undefined && parent !== null && !safe(() => api.tech.getDefinitionById(TECH_TOOLS))) {
		safe(() => api.i18n.register("en", {
			[`tech|${TECH_TOOLS}|name`]: "Mod Tools",
			[`tech|${TECH_TOOLS}|description`]:
				"Free testing toolkit, all in one: the Matter Gun (fires any material - a picker appears while it is in hand), delete buttons on every vacuum tank, and the Omni Vacuum - sucks ANY material, liquids and gases included, with 10x tank storage. Structures stay safe.",
		}));
		const definition = {
			nameKey: `tech|${TECH_TOOLS}|name`,
			descriptionKey: `tech|${TECH_TOOLS}|description`,
			cost: 0,
			currencyType: "gold",
			branch: "heat",
			requires: [parent],
			unlocks: { items: [GUN] },
		};
		// The Shaker root sits at grid {row 0, col 4} (verified in the tree code):
		// park Mod Tools right beside it on the top row, walking outward until a
		// cell is free. Occupied cells throw, so the loop just tries the next.
		let done = false;
		for (const preferredPosition of [{ row: 0, col: 5 }, { row: 0, col: 3 }, { row: 0, col: 6 }, { row: 0, col: 2 }, { row: 1, col: 4 }, null]) {
			try {
				api.tech.registerNode(TECH_TOOLS, definition,
					preferredPosition ? { parentId: parent, preferredPosition } : { parentId: parent });
				console.log(`[${MOD_ID}] research node registered: Mod Tools (free, off the Shaker)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Mod Tools node could not be placed`);
	}
}



// =========================================================================
// MANUFACTURING & GLASS research
//
// Manufacturing sits immediately LEFT of the Smelter in the tech tree
// (Smelter is grid row 13, col 1 - verified in the vanilla layout table),
// and is the trunk future branches will hang off. GLASS is its first
// child: researching it registers the Sand -> Glass smelter recipe, which
// does not exist until then - un-researched, the Smelter ignores Sand.
// =========================================================================

const TECH_MANU = "brandonManufacturing";
const TECH_GLASS = "brandonGlassTech";

safe(() => api.i18n.register("en", {
	[`tech|${TECH_MANU}|name`]: "Manufacturing",
	[`tech|${TECH_MANU}|description`]:
		"Industrial processing of raw desert materials. Unlocks the manufacturing branch - Glass first, more to come.",
	[`tech|${TECH_GLASS}|name`]: "Glass",
	[`tech|${TECH_GLASS}|description`]:
		"Glassmaking. The Smelter learns to convert Sand 1:1 into Glass, a pale solid just light enough to clear the machine.",
}));

// Manufacturing - left of the Smelter (row 13, col 0), child of Smelter tech.
{
	const parent = safe(() => sandkit.enums.Tech.Smelter);
	if (parent !== undefined && parent !== null && !safe(() => api.tech.getDefinitionById(TECH_MANU))) {
		const definition = {
			nameKey: `tech|${TECH_MANU}|name`,
			descriptionKey: `tech|${TECH_MANU}|description`,
			cost: 250,
			currencyType: "gold",
			branch: "heat",
			requires: [parent],
			unlocks: {},
		};
		let done = false;
		for (const preferredPosition of [{ row: 13, col: 0 }, { row: 14, col: 1 }, { row: 12, col: 0 }, null]) {
			try {
				api.tech.registerNode(TECH_MANU, definition,
					preferredPosition ? { parentId: parent, preferredPosition } : { parentId: parent });
				console.log(`[${MOD_ID}] research node registered: Manufacturing (left of the Smelter)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Manufacturing node could not be placed`);
	}
}

// Glass - first branch under Manufacturing (row 14, col 0).
{
	if (safe(() => api.tech.getDefinitionById(TECH_MANU)) && !safe(() => api.tech.getDefinitionById(TECH_GLASS))) {
		const definition = {
			nameKey: `tech|${TECH_GLASS}|name`,
			descriptionKey: `tech|${TECH_GLASS}|description`,
			cost: 500,
			currencyType: "gold",
			branch: "heat",
			requires: [TECH_MANU],
			unlocks: {},
		};
		let done = false;
		for (const preferredPosition of [{ row: 14, col: 0 }, { row: 15, col: 0 }, { row: 15, col: 1 }, null]) {
			try {
				api.tech.registerNode(TECH_GLASS, definition,
					preferredPosition ? { parentId: TECH_MANU, preferredPosition } : { parentId: TECH_MANU });
				console.log(`[${MOD_ID}] research node registered: Glass (under Manufacturing)`);
				done = true;
				break;
			} catch (e) {
				if (/already registered/i.test(String(e && e.message))) { done = true; break; }
			}
		}
		if (!done) console.error(`[${MOD_ID}] Glass node could not be placed`);
	}
}

// The gated recipe: the Smelter learns Sand -> Glass only once GLASS is
// researched. Recipe registration is dynamic (the registry broadcasts to the
// sim threads), so a light poll arms it the moment the node unlocks - this
// session or any later one.
let glassRecipeArmed = false;
function armGlassRecipe() {
	if (glassRecipeArmed || !isEnabled()) return;
	if (safe(() => api.tech.isLockedById(TECH_GLASS)) !== false) return;
	const input = typeOf("Sand"), output = typeOf("glass");
	if (input === undefined || output === undefined) return;
	try {
		api.structures.recipes.register("smelter", { input, outputs: [{ elementType: output, chance: 1 }] });
		safe(() => api.elements.addInteractionInfo("Sand", { kind: "custom", text: "Smelter: Sand → Glass" }));
		safe(() => api.ui.toast("Glass researched - the Smelter now converts Sand into Glass"));
		console.log(`[${MOD_ID}] Glass researched: smelter recipe Sand -> Glass armed`);
	} catch (e) {
		console.error(`[${MOD_ID}] gated glass recipe failed to register:`, e);
	}
	glassRecipeArmed = true;
}
armGlassRecipe();
setInterval(armGlassRecipe, 1500);

